// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0x587/guardeye/common/ent/agent"
	"github.com/google/uuid"
)

// AgentCreate is the builder for creating a Agent entity.
type AgentCreate struct {
	config
	mutation *AgentMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (ac *AgentCreate) SetClientID(u uuid.UUID) *AgentCreate {
	ac.mutation.SetClientID(u)
	return ac
}

// SetCreateAt sets the "create_at" field.
func (ac *AgentCreate) SetCreateAt(t time.Time) *AgentCreate {
	ac.mutation.SetCreateAt(t)
	return ac
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ac *AgentCreate) SetNillableCreateAt(t *time.Time) *AgentCreate {
	if t != nil {
		ac.SetCreateAt(*t)
	}
	return ac
}

// SetUpdateAt sets the "update_at" field.
func (ac *AgentCreate) SetUpdateAt(t time.Time) *AgentCreate {
	ac.mutation.SetUpdateAt(t)
	return ac
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ac *AgentCreate) SetNillableUpdateAt(t *time.Time) *AgentCreate {
	if t != nil {
		ac.SetUpdateAt(*t)
	}
	return ac
}

// SetAlias sets the "alias" field.
func (ac *AgentCreate) SetAlias(s string) *AgentCreate {
	ac.mutation.SetAlias(s)
	return ac
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (ac *AgentCreate) SetNillableAlias(s *string) *AgentCreate {
	if s != nil {
		ac.SetAlias(*s)
	}
	return ac
}

// SetOs sets the "os" field.
func (ac *AgentCreate) SetOs(s string) *AgentCreate {
	ac.mutation.SetOs(s)
	return ac
}

// SetOsVersion sets the "os_version" field.
func (ac *AgentCreate) SetOsVersion(s string) *AgentCreate {
	ac.mutation.SetOsVersion(s)
	return ac
}

// SetIps sets the "ips" field.
func (ac *AgentCreate) SetIps(s []string) *AgentCreate {
	ac.mutation.SetIps(s)
	return ac
}

// SetMacs sets the "macs" field.
func (ac *AgentCreate) SetMacs(s []string) *AgentCreate {
	ac.mutation.SetMacs(s)
	return ac
}

// SetHostname sets the "hostname" field.
func (ac *AgentCreate) SetHostname(s string) *AgentCreate {
	ac.mutation.SetHostname(s)
	return ac
}

// Mutation returns the AgentMutation object of the builder.
func (ac *AgentCreate) Mutation() *AgentMutation {
	return ac.mutation
}

// Save creates the Agent in the database.
func (ac *AgentCreate) Save(ctx context.Context) (*Agent, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AgentCreate) SaveX(ctx context.Context) *Agent {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AgentCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AgentCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AgentCreate) defaults() {
	if _, ok := ac.mutation.CreateAt(); !ok {
		v := agent.DefaultCreateAt()
		ac.mutation.SetCreateAt(v)
	}
	if _, ok := ac.mutation.UpdateAt(); !ok {
		v := agent.DefaultUpdateAt()
		ac.mutation.SetUpdateAt(v)
	}
	if _, ok := ac.mutation.Alias(); !ok {
		v := agent.DefaultAlias
		ac.mutation.SetAlias(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AgentCreate) check() error {
	if _, ok := ac.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "Agent.client_id"`)}
	}
	if _, ok := ac.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "Agent.create_at"`)}
	}
	if _, ok := ac.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "Agent.update_at"`)}
	}
	if _, ok := ac.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Agent.alias"`)}
	}
	if _, ok := ac.mutation.Os(); !ok {
		return &ValidationError{Name: "os", err: errors.New(`ent: missing required field "Agent.os"`)}
	}
	if _, ok := ac.mutation.OsVersion(); !ok {
		return &ValidationError{Name: "os_version", err: errors.New(`ent: missing required field "Agent.os_version"`)}
	}
	if _, ok := ac.mutation.Ips(); !ok {
		return &ValidationError{Name: "ips", err: errors.New(`ent: missing required field "Agent.ips"`)}
	}
	if _, ok := ac.mutation.Macs(); !ok {
		return &ValidationError{Name: "macs", err: errors.New(`ent: missing required field "Agent.macs"`)}
	}
	if _, ok := ac.mutation.Hostname(); !ok {
		return &ValidationError{Name: "hostname", err: errors.New(`ent: missing required field "Agent.hostname"`)}
	}
	return nil
}

func (ac *AgentCreate) sqlSave(ctx context.Context) (*Agent, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AgentCreate) createSpec() (*Agent, *sqlgraph.CreateSpec) {
	var (
		_node = &Agent{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(agent.Table, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.ClientID(); ok {
		_spec.SetField(agent.FieldClientID, field.TypeUUID, value)
		_node.ClientID = value
	}
	if value, ok := ac.mutation.CreateAt(); ok {
		_spec.SetField(agent.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := ac.mutation.UpdateAt(); ok {
		_spec.SetField(agent.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	if value, ok := ac.mutation.Alias(); ok {
		_spec.SetField(agent.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := ac.mutation.Os(); ok {
		_spec.SetField(agent.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := ac.mutation.OsVersion(); ok {
		_spec.SetField(agent.FieldOsVersion, field.TypeString, value)
		_node.OsVersion = value
	}
	if value, ok := ac.mutation.Ips(); ok {
		_spec.SetField(agent.FieldIps, field.TypeJSON, value)
		_node.Ips = value
	}
	if value, ok := ac.mutation.Macs(); ok {
		_spec.SetField(agent.FieldMacs, field.TypeJSON, value)
		_node.Macs = value
	}
	if value, ok := ac.mutation.Hostname(); ok {
		_spec.SetField(agent.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	return _node, _spec
}

// AgentCreateBulk is the builder for creating many Agent entities in bulk.
type AgentCreateBulk struct {
	config
	err      error
	builders []*AgentCreate
}

// Save creates the Agent entities in the database.
func (acb *AgentCreateBulk) Save(ctx context.Context) ([]*Agent, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Agent, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AgentCreateBulk) SaveX(ctx context.Context) []*Agent {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AgentCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AgentCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
