syntax = "proto3";

package report;
option go_package = "./report";

message FeaturesReq{
  FeatureTransDelayReq trans_delay = 1;
}

message DelayResult {
  int64 sendDelay = 1;
  int64 receiveDelay = 2;
}

message FeatureTransDelayReq{
  bool enable = 1;
  int64 last_send_timestamp = 2;
  int64 last_receive_timestamp = 3;
  int64 sent_at_timestamp = 4;
}

message NodeDescription{
  string os = 1;
  string os_version = 2;
  repeated string ips = 3;
  repeated string macs = 4;
  string hostname = 5;
}

message NodeInfo {
  string client_id = 1;
  NodeDescription node_description = 2;
}

message Provider{
  string type = 1;
  repeated string args = 2;
}

enum LogType {
  TEXT = 0;
  YAML = 1;
  JSON = 2;
}

message Log {
  string message = 1;
  Provider provider = 2;
  LogType type = 3;
  uint64 report_at_milli = 4;
}

message LogReportReq {
  NodeInfo node_info = 1;
  repeated Log logs = 2;
  FeaturesReq features = 10;
}

message TraceSpan {
  string name = 1;
  string action = 2;
  uint64 time = 3;
}

message MQLogFlag {
  bool json_able = 1;
  bool yaml_able = 2;
}

message MQLog {
  Log log = 1;
  NodeInfo node_info = 2;
  string timestamp = 3 [json_name = "@timestamp"];
  map<string, string> parsed = 4;
  MQLogFlag flag = 5;
  repeated TraceSpan trace = 10;
}

enum ReportResultCode {
  SUCCESS = 0;
  FAILED = 1;
};

message FeaturesRsp{
  FeatureTransDelayRsp trans_delay = 1;
}

message FeatureTransDelayRsp{
  bool enable = 1;
  int64 sent_at_timestamp = 2;
}

message LogReportRsp{
  ReportResultCode code = 1;
  FeaturesRsp features = 2;
}

message InitReq{
  NodeDescription node_description = 1;
}

message InitRsp{
  NodeInfo node_info = 1;
}

enum MetricType {
  MetricType_UNKNOWN = 0;
  Number = 1;
  String = 2;
}

enum MetricFilterOp {
  MetricFilterOp_UNKNOWN = 0;
  EQ = 1;
  NE = 2;
}

message MetricFilter {
  MetricQuery metric = 1;
  MetricFilterOp op = 2;
  string value = 3;
}

message MetricQuery {
  MetricType type = 1;
  string name = 2;
  string parse_path = 3;
  repeated MetricFilter filters = 4;
}

enum LinkAction {
  LinkActionUnknown = 0;
  LinkActionPing = 1;
  LinkActionPong = 2;
}

message LinkReq{
  //流请求参数
  string question = 1;
}

message LinkRsp{
  //流响应数据
  string answer = 1;
}

service Report {
  rpc Init(InitReq) returns(InitRsp);
  rpc LogReport(LogReportReq) returns(LogReportRsp);
  rpc Link(stream LinkReq) returns(stream LinkRsp){};
}
