// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

public final class Main {
  private Main() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmain.proto\032\013pkg_b.proto\032\013pkg_c.proto\032\024" +
      "rcl_interfaces.proto\032\030builtin_interfaces" +
      ".proto\032\022shawn_define.proto\032\016std_msgs.pro" +
      "to\032\013pkg_d.proto\032\013pkg_a.proto2\355\023\n\003Api\022^\n\034" +
      "PublishTopicParameter_events\022\036.rcl_inter" +
      "faces.ParameterEvent\032\036.rcl_interfaces.Pa" +
      "rameterEvent\022>\n\022PublishTopicRosout\022\023.rcl" +
      "_interfaces.Log\032\023.rcl_interfaces.Log\0229\n\023" +
      "PublishTopicChatter\022\020.std_msgs.String\032\020." +
      "std_msgs.String\022v\n&CallServiceListenerDe" +
      "scribe_parameters\022%.rcl_interfaces.Descr" +
      "ibeParametersReq\032%.rcl_interfaces.Descri" +
      "beParametersRsp\022g\n!CallServiceListenerGe" +
      "t_parameters\022 .rcl_interfaces.GetParamet" +
      "ersReq\032 .rcl_interfaces.GetParametersRsp" +
      "\022p\n*CallServiceService_server_02Set_para" +
      "meters\022 .rcl_interfaces.SetParametersReq" +
      "\032 .rcl_interfaces.SetParametersRsp\022p\n*Ca" +
      "llServiceService_server_02Get_parameters" +
      "\022 .rcl_interfaces.GetParametersReq\032 .rcl" +
      "_interfaces.GetParametersRsp\022}\n/CallServ" +
      "iceService_server_02Get_parameter_types\022" +
      "$.rcl_interfaces.GetParameterTypesReq\032$." +
      "rcl_interfaces.GetParameterTypesRsp\022\215\001\n3" +
      "CallServiceFoxglove_bridgeSet_parameters" +
      "_atomically\022*.rcl_interfaces.SetParamete" +
      "rsAtomicallyReq\032*.rcl_interfaces.SetPara" +
      "metersAtomicallyRsp\022\177\n/CallServiceServic" +
      "e_server_02Describe_parameters\022%.rcl_int" +
      "erfaces.DescribeParametersReq\032%.rcl_inte" +
      "rfaces.DescribeParametersRsp\022j\n\"CallServ" +
      "iceListenerList_parameters\022!.rcl_interfa" +
      "ces.ListParametersReq\032!.rcl_interfaces.L" +
      "istParametersRsp\022{\n-CallServiceFoxglove_" +
      "bridgeGet_parameter_types\022$.rcl_interfac" +
      "es.GetParameterTypesReq\032$.rcl_interfaces" +
      ".GetParameterTypesRsp\022I\n\033CallServiceAdd_" +
      "two_ints_srv\022\024.shawn_define.AddReq\032\024.sha" +
      "wn_define.AddRsp\022A\n\025CallServiceGet_perso" +
      "n\022\023.pkg_d.GetPersonReq\032\023.pkg_d.GetPerson" +
      "Rsp\022t\n&CallServiceListenerGet_parameter_" +
      "types\022$.rcl_interfaces.GetParameterTypes" +
      "Req\032$.rcl_interfaces.GetParameterTypesRs" +
      "p\022q\n)CallServiceFoxglove_bridgeList_para" +
      "meters\022!.rcl_interfaces.ListParametersRe" +
      "q\032!.rcl_interfaces.ListParametersRsp\022\206\001\n" +
      ",CallServiceListenerSet_parameters_atomi" +
      "cally\022*.rcl_interfaces.SetParametersAtom" +
      "icallyReq\032*.rcl_interfaces.SetParameters" +
      "AtomicallyRsp\022n\n(CallServiceFoxglove_bri" +
      "dgeSet_parameters\022 .rcl_interfaces.SetPa" +
      "rametersReq\032 .rcl_interfaces.SetParamete" +
      "rsRsp\022s\n+CallServiceService_server_02Lis" +
      "t_parameters\022!.rcl_interfaces.ListParame" +
      "tersReq\032!.rcl_interfaces.ListParametersR" +
      "sp\022}\n-CallServiceFoxglove_bridgeDescribe" +
      "_parameters\022%.rcl_interfaces.DescribePar" +
      "ametersReq\032%.rcl_interfaces.DescribePara" +
      "metersRsp\022\217\001\n5CallServiceService_server_" +
      "02Set_parameters_atomically\022*.rcl_interf" +
      "aces.SetParametersAtomicallyReq\032*.rcl_in" +
      "terfaces.SetParametersAtomicallyRsp\022n\n(C" +
      "allServiceFoxglove_bridgeGet_parameters\022" +
      " .rcl_interfaces.GetParametersReq\032 .rcl_" +
      "interfaces.GetParametersRsp\022g\n!CallServi" +
      "ceListenerSet_parameters\022 .rcl_interface" +
      "s.SetParametersReq\032 .rcl_interfaces.SetP" +
      "arametersRspB\006Z\004./pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pkg_b.PkgB.getDescriptor(),
          pkg_c.PkgC.getDescriptor(),
          rcl_interfaces.RclInterfaces.getDescriptor(),
          builtin_interfaces.BuiltinInterfaces.getDescriptor(),
          shawn_define.ShawnDefine.getDescriptor(),
          std_msgs.StdMsgs.getDescriptor(),
          pkg_d.PkgD.getDescriptor(),
          pkg_a.PkgA.getDescriptor(),
        });
    pkg_b.PkgB.getDescriptor();
    pkg_c.PkgC.getDescriptor();
    rcl_interfaces.RclInterfaces.getDescriptor();
    builtin_interfaces.BuiltinInterfaces.getDescriptor();
    shawn_define.ShawnDefine.getDescriptor();
    std_msgs.StdMsgs.getDescriptor();
    pkg_d.PkgD.getDescriptor();
    pkg_a.PkgA.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
