// Code generated by goctl. DO NOT EDIT.
package types

type GetDataKeysReq struct {
	Id string `path:"id"`
}

type GetDataKeysRsp struct {
	Keys []ProviderKeys `json:"keys"`
}

type InitRsp struct {
	WsMsgBase
	SessionId string `json:"sessionId"`
}

type Metric struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type MetricRsp struct {
	WsMsgBase
	Metrics []Metric `json:"metrics"`
}

type NodeInfo struct {
	Id         string   `json:"id"`
	Alias      string   `json:"alias"`
	Macs       []string `json:"macs"`
	Ips        []string `json:"ips"`
	LastSeenAt string   `json:"lastSeenAt"`
}

type NodesReq struct {
}

type NodesRsp struct {
	Nodes []NodeInfo `json:"nodes"`
}

type Provider struct {
	Ptype string   `json:"type"`
	Args  []string `json:"args"`
	Str   string   `json:"str,optional"`
}

type ProviderKey struct {
	Provider Provider `json:"provider"`
	Key      string   `json:"key"`
}

type ProviderKeys struct {
	Provider Provider `json:"provider"`
	Keys     []string `json:"keys"`
}

type SetAliasReq struct {
	Id    string `path:"id"`
	Alias string `json:"alias"`
}

type SetAliasRsp struct {
	Ok bool `json:"ok"`
}

type SetListenReq struct {
	SessionId string         `json:"sessionId"`
	NodeId    string         `json:"nodeId"`
	Keys      []ProviderKeys `json:"keys"`
}

type WsMsgBase struct {
	Cmd string `json:"cmd"`
}
