// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: foxglove_service.proto

package foxgloveService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoxgloveService_CdrRead_FullMethodName  = "/FoxgloveService.FoxgloveService/CdrRead"
	FoxgloveService_CdrWrite_FullMethodName = "/FoxgloveService.FoxgloveService/CdrWrite"
)

// FoxgloveServiceClient is the client API for FoxgloveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoxgloveServiceClient interface {
	CdrRead(ctx context.Context, in *CdrReadReq, opts ...grpc.CallOption) (*CdrReadRsp, error)
	CdrWrite(ctx context.Context, in *CdrWriteReq, opts ...grpc.CallOption) (*CdrWriteRsp, error)
}

type foxgloveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoxgloveServiceClient(cc grpc.ClientConnInterface) FoxgloveServiceClient {
	return &foxgloveServiceClient{cc}
}

func (c *foxgloveServiceClient) CdrRead(ctx context.Context, in *CdrReadReq, opts ...grpc.CallOption) (*CdrReadRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CdrReadRsp)
	err := c.cc.Invoke(ctx, FoxgloveService_CdrRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foxgloveServiceClient) CdrWrite(ctx context.Context, in *CdrWriteReq, opts ...grpc.CallOption) (*CdrWriteRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CdrWriteRsp)
	err := c.cc.Invoke(ctx, FoxgloveService_CdrWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoxgloveServiceServer is the server API for FoxgloveService service.
// All implementations must embed UnimplementedFoxgloveServiceServer
// for forward compatibility.
type FoxgloveServiceServer interface {
	CdrRead(context.Context, *CdrReadReq) (*CdrReadRsp, error)
	CdrWrite(context.Context, *CdrWriteReq) (*CdrWriteRsp, error)
	mustEmbedUnimplementedFoxgloveServiceServer()
}

// UnimplementedFoxgloveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoxgloveServiceServer struct{}

func (UnimplementedFoxgloveServiceServer) CdrRead(context.Context, *CdrReadReq) (*CdrReadRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CdrRead not implemented")
}
func (UnimplementedFoxgloveServiceServer) CdrWrite(context.Context, *CdrWriteReq) (*CdrWriteRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CdrWrite not implemented")
}
func (UnimplementedFoxgloveServiceServer) mustEmbedUnimplementedFoxgloveServiceServer() {}
func (UnimplementedFoxgloveServiceServer) testEmbeddedByValue()                         {}

// UnsafeFoxgloveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoxgloveServiceServer will
// result in compilation errors.
type UnsafeFoxgloveServiceServer interface {
	mustEmbedUnimplementedFoxgloveServiceServer()
}

func RegisterFoxgloveServiceServer(s grpc.ServiceRegistrar, srv FoxgloveServiceServer) {
	// If the following call pancis, it indicates UnimplementedFoxgloveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoxgloveService_ServiceDesc, srv)
}

func _FoxgloveService_CdrRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CdrReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoxgloveServiceServer).CdrRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoxgloveService_CdrRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoxgloveServiceServer).CdrRead(ctx, req.(*CdrReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoxgloveService_CdrWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CdrWriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoxgloveServiceServer).CdrWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoxgloveService_CdrWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoxgloveServiceServer).CdrWrite(ctx, req.(*CdrWriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FoxgloveService_ServiceDesc is the grpc.ServiceDesc for FoxgloveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoxgloveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FoxgloveService.FoxgloveService",
	HandlerType: (*FoxgloveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CdrRead",
			Handler:    _FoxgloveService_CdrRead_Handler,
		},
		{
			MethodName: "CdrWrite",
			Handler:    _FoxgloveService_CdrWrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foxglove_service.proto",
}
