// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/0x587/guardeye/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/node/:id/alias",
				Handler: SetAliasHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/node/:id/data/keys",
				Handler: GetDataKeysHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/nodes",
				Handler: NodesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws/node/:id",
				Handler: NodeWsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
