// Code generated by ent, DO NOT EDIT.

package subscribe

import (
	"entgo.io/ent/dialect/sql"
	"github.com/0x587/guardeye/common/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLTE(FieldID, id))
}

// Enable applies equality check predicate on the "enable" field. It's identical to EnableEQ.
func Enable(v bool) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldEnable, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldQuery, v))
}

// WebHookURL applies equality check predicate on the "web_hook_url" field. It's identical to WebHookURLEQ.
func WebHookURL(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldWebHookURL, v))
}

// MqttPushURL applies equality check predicate on the "mqtt_push_url" field. It's identical to MqttPushURLEQ.
func MqttPushURL(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldMqttPushURL, v))
}

// MqttPushTopic applies equality check predicate on the "mqtt_push_topic" field. It's identical to MqttPushTopicEQ.
func MqttPushTopic(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldMqttPushTopic, v))
}

// WebSocketKey applies equality check predicate on the "web_socket_key" field. It's identical to WebSocketKeyEQ.
func WebSocketKey(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldWebSocketKey, v))
}

// EnableEQ applies the EQ predicate on the "enable" field.
func EnableEQ(v bool) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldEnable, v))
}

// EnableNEQ applies the NEQ predicate on the "enable" field.
func EnableNEQ(v bool) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldEnable, v))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContainsFold(FieldQuery, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldType, vs...))
}

// WebHookURLEQ applies the EQ predicate on the "web_hook_url" field.
func WebHookURLEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldWebHookURL, v))
}

// WebHookURLNEQ applies the NEQ predicate on the "web_hook_url" field.
func WebHookURLNEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldWebHookURL, v))
}

// WebHookURLIn applies the In predicate on the "web_hook_url" field.
func WebHookURLIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldWebHookURL, vs...))
}

// WebHookURLNotIn applies the NotIn predicate on the "web_hook_url" field.
func WebHookURLNotIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldWebHookURL, vs...))
}

// WebHookURLGT applies the GT predicate on the "web_hook_url" field.
func WebHookURLGT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGT(FieldWebHookURL, v))
}

// WebHookURLGTE applies the GTE predicate on the "web_hook_url" field.
func WebHookURLGTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGTE(FieldWebHookURL, v))
}

// WebHookURLLT applies the LT predicate on the "web_hook_url" field.
func WebHookURLLT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLT(FieldWebHookURL, v))
}

// WebHookURLLTE applies the LTE predicate on the "web_hook_url" field.
func WebHookURLLTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLTE(FieldWebHookURL, v))
}

// WebHookURLContains applies the Contains predicate on the "web_hook_url" field.
func WebHookURLContains(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContains(FieldWebHookURL, v))
}

// WebHookURLHasPrefix applies the HasPrefix predicate on the "web_hook_url" field.
func WebHookURLHasPrefix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasPrefix(FieldWebHookURL, v))
}

// WebHookURLHasSuffix applies the HasSuffix predicate on the "web_hook_url" field.
func WebHookURLHasSuffix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasSuffix(FieldWebHookURL, v))
}

// WebHookURLIsNil applies the IsNil predicate on the "web_hook_url" field.
func WebHookURLIsNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIsNull(FieldWebHookURL))
}

// WebHookURLNotNil applies the NotNil predicate on the "web_hook_url" field.
func WebHookURLNotNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotNull(FieldWebHookURL))
}

// WebHookURLEqualFold applies the EqualFold predicate on the "web_hook_url" field.
func WebHookURLEqualFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEqualFold(FieldWebHookURL, v))
}

// WebHookURLContainsFold applies the ContainsFold predicate on the "web_hook_url" field.
func WebHookURLContainsFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContainsFold(FieldWebHookURL, v))
}

// MqttPushURLEQ applies the EQ predicate on the "mqtt_push_url" field.
func MqttPushURLEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldMqttPushURL, v))
}

// MqttPushURLNEQ applies the NEQ predicate on the "mqtt_push_url" field.
func MqttPushURLNEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldMqttPushURL, v))
}

// MqttPushURLIn applies the In predicate on the "mqtt_push_url" field.
func MqttPushURLIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldMqttPushURL, vs...))
}

// MqttPushURLNotIn applies the NotIn predicate on the "mqtt_push_url" field.
func MqttPushURLNotIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldMqttPushURL, vs...))
}

// MqttPushURLGT applies the GT predicate on the "mqtt_push_url" field.
func MqttPushURLGT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGT(FieldMqttPushURL, v))
}

// MqttPushURLGTE applies the GTE predicate on the "mqtt_push_url" field.
func MqttPushURLGTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGTE(FieldMqttPushURL, v))
}

// MqttPushURLLT applies the LT predicate on the "mqtt_push_url" field.
func MqttPushURLLT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLT(FieldMqttPushURL, v))
}

// MqttPushURLLTE applies the LTE predicate on the "mqtt_push_url" field.
func MqttPushURLLTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLTE(FieldMqttPushURL, v))
}

// MqttPushURLContains applies the Contains predicate on the "mqtt_push_url" field.
func MqttPushURLContains(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContains(FieldMqttPushURL, v))
}

// MqttPushURLHasPrefix applies the HasPrefix predicate on the "mqtt_push_url" field.
func MqttPushURLHasPrefix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasPrefix(FieldMqttPushURL, v))
}

// MqttPushURLHasSuffix applies the HasSuffix predicate on the "mqtt_push_url" field.
func MqttPushURLHasSuffix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasSuffix(FieldMqttPushURL, v))
}

// MqttPushURLIsNil applies the IsNil predicate on the "mqtt_push_url" field.
func MqttPushURLIsNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIsNull(FieldMqttPushURL))
}

// MqttPushURLNotNil applies the NotNil predicate on the "mqtt_push_url" field.
func MqttPushURLNotNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotNull(FieldMqttPushURL))
}

// MqttPushURLEqualFold applies the EqualFold predicate on the "mqtt_push_url" field.
func MqttPushURLEqualFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEqualFold(FieldMqttPushURL, v))
}

// MqttPushURLContainsFold applies the ContainsFold predicate on the "mqtt_push_url" field.
func MqttPushURLContainsFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContainsFold(FieldMqttPushURL, v))
}

// MqttPushTopicEQ applies the EQ predicate on the "mqtt_push_topic" field.
func MqttPushTopicEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldMqttPushTopic, v))
}

// MqttPushTopicNEQ applies the NEQ predicate on the "mqtt_push_topic" field.
func MqttPushTopicNEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldMqttPushTopic, v))
}

// MqttPushTopicIn applies the In predicate on the "mqtt_push_topic" field.
func MqttPushTopicIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldMqttPushTopic, vs...))
}

// MqttPushTopicNotIn applies the NotIn predicate on the "mqtt_push_topic" field.
func MqttPushTopicNotIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldMqttPushTopic, vs...))
}

// MqttPushTopicGT applies the GT predicate on the "mqtt_push_topic" field.
func MqttPushTopicGT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGT(FieldMqttPushTopic, v))
}

// MqttPushTopicGTE applies the GTE predicate on the "mqtt_push_topic" field.
func MqttPushTopicGTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGTE(FieldMqttPushTopic, v))
}

// MqttPushTopicLT applies the LT predicate on the "mqtt_push_topic" field.
func MqttPushTopicLT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLT(FieldMqttPushTopic, v))
}

// MqttPushTopicLTE applies the LTE predicate on the "mqtt_push_topic" field.
func MqttPushTopicLTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLTE(FieldMqttPushTopic, v))
}

// MqttPushTopicContains applies the Contains predicate on the "mqtt_push_topic" field.
func MqttPushTopicContains(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContains(FieldMqttPushTopic, v))
}

// MqttPushTopicHasPrefix applies the HasPrefix predicate on the "mqtt_push_topic" field.
func MqttPushTopicHasPrefix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasPrefix(FieldMqttPushTopic, v))
}

// MqttPushTopicHasSuffix applies the HasSuffix predicate on the "mqtt_push_topic" field.
func MqttPushTopicHasSuffix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasSuffix(FieldMqttPushTopic, v))
}

// MqttPushTopicIsNil applies the IsNil predicate on the "mqtt_push_topic" field.
func MqttPushTopicIsNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIsNull(FieldMqttPushTopic))
}

// MqttPushTopicNotNil applies the NotNil predicate on the "mqtt_push_topic" field.
func MqttPushTopicNotNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotNull(FieldMqttPushTopic))
}

// MqttPushTopicEqualFold applies the EqualFold predicate on the "mqtt_push_topic" field.
func MqttPushTopicEqualFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEqualFold(FieldMqttPushTopic, v))
}

// MqttPushTopicContainsFold applies the ContainsFold predicate on the "mqtt_push_topic" field.
func MqttPushTopicContainsFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContainsFold(FieldMqttPushTopic, v))
}

// WebSocketKeyEQ applies the EQ predicate on the "web_socket_key" field.
func WebSocketKeyEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEQ(FieldWebSocketKey, v))
}

// WebSocketKeyNEQ applies the NEQ predicate on the "web_socket_key" field.
func WebSocketKeyNEQ(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNEQ(FieldWebSocketKey, v))
}

// WebSocketKeyIn applies the In predicate on the "web_socket_key" field.
func WebSocketKeyIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIn(FieldWebSocketKey, vs...))
}

// WebSocketKeyNotIn applies the NotIn predicate on the "web_socket_key" field.
func WebSocketKeyNotIn(vs ...string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotIn(FieldWebSocketKey, vs...))
}

// WebSocketKeyGT applies the GT predicate on the "web_socket_key" field.
func WebSocketKeyGT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGT(FieldWebSocketKey, v))
}

// WebSocketKeyGTE applies the GTE predicate on the "web_socket_key" field.
func WebSocketKeyGTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldGTE(FieldWebSocketKey, v))
}

// WebSocketKeyLT applies the LT predicate on the "web_socket_key" field.
func WebSocketKeyLT(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLT(FieldWebSocketKey, v))
}

// WebSocketKeyLTE applies the LTE predicate on the "web_socket_key" field.
func WebSocketKeyLTE(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldLTE(FieldWebSocketKey, v))
}

// WebSocketKeyContains applies the Contains predicate on the "web_socket_key" field.
func WebSocketKeyContains(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContains(FieldWebSocketKey, v))
}

// WebSocketKeyHasPrefix applies the HasPrefix predicate on the "web_socket_key" field.
func WebSocketKeyHasPrefix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasPrefix(FieldWebSocketKey, v))
}

// WebSocketKeyHasSuffix applies the HasSuffix predicate on the "web_socket_key" field.
func WebSocketKeyHasSuffix(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldHasSuffix(FieldWebSocketKey, v))
}

// WebSocketKeyIsNil applies the IsNil predicate on the "web_socket_key" field.
func WebSocketKeyIsNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldIsNull(FieldWebSocketKey))
}

// WebSocketKeyNotNil applies the NotNil predicate on the "web_socket_key" field.
func WebSocketKeyNotNil() predicate.Subscribe {
	return predicate.Subscribe(sql.FieldNotNull(FieldWebSocketKey))
}

// WebSocketKeyEqualFold applies the EqualFold predicate on the "web_socket_key" field.
func WebSocketKeyEqualFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldEqualFold(FieldWebSocketKey, v))
}

// WebSocketKeyContainsFold applies the ContainsFold predicate on the "web_socket_key" field.
func WebSocketKeyContainsFold(v string) predicate.Subscribe {
	return predicate.Subscribe(sql.FieldContainsFold(FieldWebSocketKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscribe) predicate.Subscribe {
	return predicate.Subscribe(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscribe) predicate.Subscribe {
	return predicate.Subscribe(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscribe) predicate.Subscribe {
	return predicate.Subscribe(sql.NotPredicates(p))
}
