// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.4
// source: link.proto

package link

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RosTypeGenType int32

const (
	RosTypeGenType_MESSAGE RosTypeGenType = 0
	RosTypeGenType_SERVICE RosTypeGenType = 1
)

// Enum value maps for RosTypeGenType.
var (
	RosTypeGenType_name = map[int32]string{
		0: "MESSAGE",
		1: "SERVICE",
	}
	RosTypeGenType_value = map[string]int32{
		"MESSAGE": 0,
		"SERVICE": 1,
	}
)

func (x RosTypeGenType) Enum() *RosTypeGenType {
	p := new(RosTypeGenType)
	*p = x
	return p
}

func (x RosTypeGenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RosTypeGenType) Descriptor() protoreflect.EnumDescriptor {
	return file_link_proto_enumTypes[0].Descriptor()
}

func (RosTypeGenType) Type() protoreflect.EnumType {
	return &file_link_proto_enumTypes[0]
}

func (x RosTypeGenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RosTypeGenType.Descriptor instead.
func (RosTypeGenType) EnumDescriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

type LinkCallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid    string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LinkCallReq) Reset() {
	*x = LinkCallReq{}
	mi := &file_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCallReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCallReq) ProtoMessage() {}

func (x *LinkCallReq) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCallReq.ProtoReflect.Descriptor instead.
func (*LinkCallReq) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{1}
}

func (x *LinkCallReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *LinkCallReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LinkCallReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LinkCallRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LinkCallRsp) Reset() {
	*x = LinkCallRsp{}
	mi := &file_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCallRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCallRsp) ProtoMessage() {}

func (x *LinkCallRsp) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCallRsp.ProtoReflect.Descriptor instead.
func (*LinkCallRsp) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{2}
}

func (x *LinkCallRsp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LinkCommandDownstream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PayloadRosExec *LinkCommandPayloadRosExec `protobuf:"bytes,2,opt,name=payload_ros_exec,json=payloadRosExec,proto3" json:"payload_ros_exec,omitempty"`
	PayloadRosType *LinkCommandPayloadRosType `protobuf:"bytes,3,opt,name=payload_ros_type,json=payloadRosType,proto3" json:"payload_ros_type,omitempty"`
	PayloadRosList *LinkCommandPayloadRosList `protobuf:"bytes,4,opt,name=payload_ros_list,json=payloadRosList,proto3" json:"payload_ros_list,omitempty"`
}

func (x *LinkCommandDownstream) Reset() {
	*x = LinkCommandDownstream{}
	mi := &file_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCommandDownstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCommandDownstream) ProtoMessage() {}

func (x *LinkCommandDownstream) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCommandDownstream.ProtoReflect.Descriptor instead.
func (*LinkCommandDownstream) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{3}
}

func (x *LinkCommandDownstream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LinkCommandDownstream) GetPayloadRosExec() *LinkCommandPayloadRosExec {
	if x != nil {
		return x.PayloadRosExec
	}
	return nil
}

func (x *LinkCommandDownstream) GetPayloadRosType() *LinkCommandPayloadRosType {
	if x != nil {
		return x.PayloadRosType
	}
	return nil
}

func (x *LinkCommandDownstream) GetPayloadRosList() *LinkCommandPayloadRosList {
	if x != nil {
		return x.PayloadRosList
	}
	return nil
}

type LinkCommandPayloadRosExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	RosTopic string `protobuf:"bytes,2,opt,name=ros_topic,json=rosTopic,proto3" json:"ros_topic,omitempty"`
	Data     string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LinkCommandPayloadRosExec) Reset() {
	*x = LinkCommandPayloadRosExec{}
	mi := &file_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCommandPayloadRosExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCommandPayloadRosExec) ProtoMessage() {}

func (x *LinkCommandPayloadRosExec) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCommandPayloadRosExec.ProtoReflect.Descriptor instead.
func (*LinkCommandPayloadRosExec) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{4}
}

func (x *LinkCommandPayloadRosExec) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LinkCommandPayloadRosExec) GetRosTopic() string {
	if x != nil {
		return x.RosTopic
	}
	return ""
}

func (x *LinkCommandPayloadRosExec) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LinkCommandPayloadRosType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     RosTypeGenType `protobuf:"varint,1,opt,name=type,proto3,enum=link.RosTypeGenType" json:"type,omitempty"`
	RosTopic string         `protobuf:"bytes,2,opt,name=ros_topic,json=rosTopic,proto3" json:"ros_topic,omitempty"`
}

func (x *LinkCommandPayloadRosType) Reset() {
	*x = LinkCommandPayloadRosType{}
	mi := &file_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCommandPayloadRosType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCommandPayloadRosType) ProtoMessage() {}

func (x *LinkCommandPayloadRosType) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCommandPayloadRosType.ProtoReflect.Descriptor instead.
func (*LinkCommandPayloadRosType) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{5}
}

func (x *LinkCommandPayloadRosType) GetType() RosTypeGenType {
	if x != nil {
		return x.Type
	}
	return RosTypeGenType_MESSAGE
}

func (x *LinkCommandPayloadRosType) GetRosTopic() string {
	if x != nil {
		return x.RosTopic
	}
	return ""
}

type LinkCommandPayloadRosList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LinkCommandPayloadRosList) Reset() {
	*x = LinkCommandPayloadRosList{}
	mi := &file_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCommandPayloadRosList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCommandPayloadRosList) ProtoMessage() {}

func (x *LinkCommandPayloadRosList) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCommandPayloadRosList.ProtoReflect.Descriptor instead.
func (*LinkCommandPayloadRosList) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{6}
}

type LinkCommandUpstream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok             bool               `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	CdrData        string             `protobuf:"bytes,3,opt,name=cdr_data,json=cdrData,proto3" json:"cdr_data,omitempty"`
	ErrMsg         string             `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	Cid            string             `protobuf:"bytes,5,opt,name=cid,proto3" json:"cid,omitempty"` // for init connection
	TypeGenResult  *LinkTypeGenResult `protobuf:"bytes,6,opt,name=type_gen_result,json=typeGenResult,proto3" json:"type_gen_result,omitempty"`
	TypeListResult *TypeListRsp       `protobuf:"bytes,7,opt,name=type_list_result,json=typeListResult,proto3" json:"type_list_result,omitempty"`
}

func (x *LinkCommandUpstream) Reset() {
	*x = LinkCommandUpstream{}
	mi := &file_link_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCommandUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCommandUpstream) ProtoMessage() {}

func (x *LinkCommandUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCommandUpstream.ProtoReflect.Descriptor instead.
func (*LinkCommandUpstream) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{7}
}

func (x *LinkCommandUpstream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LinkCommandUpstream) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LinkCommandUpstream) GetCdrData() string {
	if x != nil {
		return x.CdrData
	}
	return ""
}

func (x *LinkCommandUpstream) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *LinkCommandUpstream) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *LinkCommandUpstream) GetTypeGenResult() *LinkTypeGenResult {
	if x != nil {
		return x.TypeGenResult
	}
	return nil
}

func (x *LinkCommandUpstream) GetTypeListResult() *TypeListRsp {
	if x != nil {
		return x.TypeListResult
	}
	return nil
}

type LinkTypeGenResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Req  string `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	Rsp  string `protobuf:"bytes,3,opt,name=rsp,proto3" json:"rsp,omitempty"`
}

func (x *LinkTypeGenResult) Reset() {
	*x = LinkTypeGenResult{}
	mi := &file_link_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkTypeGenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkTypeGenResult) ProtoMessage() {}

func (x *LinkTypeGenResult) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkTypeGenResult.ProtoReflect.Descriptor instead.
func (*LinkTypeGenResult) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{8}
}

func (x *LinkTypeGenResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkTypeGenResult) GetReq() string {
	if x != nil {
		return x.Req
	}
	return ""
}

func (x *LinkTypeGenResult) GetRsp() string {
	if x != nil {
		return x.Rsp
	}
	return ""
}

type TypeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *TypeListReq) Reset() {
	*x = TypeListReq{}
	mi := &file_link_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeListReq) ProtoMessage() {}

func (x *TypeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeListReq.ProtoReflect.Descriptor instead.
func (*TypeListReq) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{9}
}

func (x *TypeListReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type TypeListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Services []string `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *TypeListRsp) Reset() {
	*x = TypeListRsp{}
	mi := &file_link_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeListRsp) ProtoMessage() {}

func (x *TypeListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeListRsp.ProtoReflect.Descriptor instead.
func (*TypeListRsp) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{10}
}

func (x *TypeListRsp) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *TypeListRsp) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

type TypeGenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid         string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	TopicRegexp string `protobuf:"bytes,2,opt,name=topic_regexp,json=topicRegexp,proto3" json:"topic_regexp,omitempty"`
}

func (x *TypeGenReq) Reset() {
	*x = TypeGenReq{}
	mi := &file_link_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeGenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeGenReq) ProtoMessage() {}

func (x *TypeGenReq) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeGenReq.ProtoReflect.Descriptor instead.
func (*TypeGenReq) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{11}
}

func (x *TypeGenReq) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *TypeGenReq) GetTopicRegexp() string {
	if x != nil {
		return x.TopicRegexp
	}
	return ""
}

type TypeGenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pb map[string]string `protobuf:"bytes,1,rep,name=pb,proto3" json:"pb,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TypeGenRsp) Reset() {
	*x = TypeGenRsp{}
	mi := &file_link_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeGenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeGenRsp) ProtoMessage() {}

func (x *TypeGenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeGenRsp.ProtoReflect.Descriptor instead.
func (*TypeGenRsp) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{12}
}

func (x *TypeGenRsp) GetPb() map[string]string {
	if x != nil {
		return x.Pb
	}
	return nil
}

type TypeSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RosSchema  string `protobuf:"bytes,1,opt,name=ros_schema,json=rosSchema,proto3" json:"ros_schema,omitempty"`
	PbSchema   string `protobuf:"bytes,2,opt,name=pb_schema,json=pbSchema,proto3" json:"pb_schema,omitempty"`
	PbTypeName string `protobuf:"bytes,3,opt,name=pb_type_name,json=pbTypeName,proto3" json:"pb_type_name,omitempty"`
}

func (x *TypeSchema) Reset() {
	*x = TypeSchema{}
	mi := &file_link_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeSchema) ProtoMessage() {}

func (x *TypeSchema) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeSchema.ProtoReflect.Descriptor instead.
func (*TypeSchema) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{13}
}

func (x *TypeSchema) GetRosSchema() string {
	if x != nil {
		return x.RosSchema
	}
	return ""
}

func (x *TypeSchema) GetPbSchema() string {
	if x != nil {
		return x.PbSchema
	}
	return ""
}

func (x *TypeSchema) GetPbTypeName() string {
	if x != nil {
		return x.PbTypeName
	}
	return ""
}

type AgentListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents map[string]string `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AgentListRsp) Reset() {
	*x = AgentListRsp{}
	mi := &file_link_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentListRsp) ProtoMessage() {}

func (x *AgentListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentListRsp.ProtoReflect.Descriptor instead.
func (*AgentListRsp) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{14}
}

func (x *AgentListRsp) GetAgents() map[string]string {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_link_proto protoreflect.FileDescriptor

var file_link_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x4b, 0x0a, 0x0b, 0x4c,
	0x69, 0x6e, 0x6b, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x6b,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x88, 0x02, 0x0a, 0x15,
	0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x6f, 0x77, 0x6e, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x49, 0x0a, 0x10, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x72, 0x6f, 0x73, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x73, 0x45, 0x78, 0x65, 0x63,
	0x52, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x73, 0x45, 0x78, 0x65, 0x63,
	0x12, 0x49, 0x0a, 0x10, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x72, 0x6f, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x49, 0x0a, 0x10, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x72, 0x6f, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4c, 0x69, 0x6e,
	0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x64, 0x0a, 0x19, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x73, 0x45,
	0x78, 0x65, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x6f, 0x73, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x6f, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x19,
	0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x52,
	0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x73, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xf9, 0x01,
	0x0a, 0x13, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x64, 0x72, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x64, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x3f, 0x0a, 0x0f, 0x74,
	0x79, 0x70, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x74,
	0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x10,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x52, 0x0e, 0x74, 0x79, 0x70, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4b, 0x0a, 0x11, 0x4c, 0x69, 0x6e,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x72, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x72, 0x73, 0x70, 0x22, 0x1f, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x41,
	0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x67, 0x65, 0x78,
	0x70, 0x22, 0x6d, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12,
	0x28, 0x0a, 0x02, 0x70, 0x62, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x69,
	0x6e, 0x6b, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x2e, 0x50, 0x62,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x02, 0x70, 0x62, 0x1a, 0x35, 0x0a, 0x07, 0x50, 0x62, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x6a, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x73, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x62, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x62, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x62,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x81, 0x01, 0x0a,
	0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a,
	0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x2a, 0x2a, 0x0a, 0x0e, 0x52, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x32, 0x8b, 0x02, 0x0a,
	0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x42, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x19, 0x2e,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x1b, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x6f, 0x77, 0x6e, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x28, 0x01, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x08, 0x4c, 0x69, 0x6e,
	0x6b, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4c, 0x69, 0x6e,
	0x6b, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x08, 0x54,
	0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2d, 0x0a,
	0x07, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x12, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x09,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_link_proto_rawDescOnce sync.Once
	file_link_proto_rawDescData = file_link_proto_rawDesc
)

func file_link_proto_rawDescGZIP() []byte {
	file_link_proto_rawDescOnce.Do(func() {
		file_link_proto_rawDescData = protoimpl.X.CompressGZIP(file_link_proto_rawDescData)
	})
	return file_link_proto_rawDescData
}

var file_link_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_link_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_link_proto_goTypes = []any{
	(RosTypeGenType)(0),               // 0: link.RosTypeGenType
	(*Empty)(nil),                     // 1: link.Empty
	(*LinkCallReq)(nil),               // 2: link.LinkCallReq
	(*LinkCallRsp)(nil),               // 3: link.LinkCallRsp
	(*LinkCommandDownstream)(nil),     // 4: link.LinkCommandDownstream
	(*LinkCommandPayloadRosExec)(nil), // 5: link.LinkCommandPayloadRosExec
	(*LinkCommandPayloadRosType)(nil), // 6: link.LinkCommandPayloadRosType
	(*LinkCommandPayloadRosList)(nil), // 7: link.LinkCommandPayloadRosList
	(*LinkCommandUpstream)(nil),       // 8: link.LinkCommandUpstream
	(*LinkTypeGenResult)(nil),         // 9: link.LinkTypeGenResult
	(*TypeListReq)(nil),               // 10: link.TypeListReq
	(*TypeListRsp)(nil),               // 11: link.TypeListRsp
	(*TypeGenReq)(nil),                // 12: link.TypeGenReq
	(*TypeGenRsp)(nil),                // 13: link.TypeGenRsp
	(*TypeSchema)(nil),                // 14: link.TypeSchema
	(*AgentListRsp)(nil),              // 15: link.AgentListRsp
	nil,                               // 16: link.TypeGenRsp.PbEntry
	nil,                               // 17: link.AgentListRsp.AgentsEntry
}
var file_link_proto_depIdxs = []int32{
	5,  // 0: link.LinkCommandDownstream.payload_ros_exec:type_name -> link.LinkCommandPayloadRosExec
	6,  // 1: link.LinkCommandDownstream.payload_ros_type:type_name -> link.LinkCommandPayloadRosType
	7,  // 2: link.LinkCommandDownstream.payload_ros_list:type_name -> link.LinkCommandPayloadRosList
	0,  // 3: link.LinkCommandPayloadRosType.type:type_name -> link.RosTypeGenType
	9,  // 4: link.LinkCommandUpstream.type_gen_result:type_name -> link.LinkTypeGenResult
	11, // 5: link.LinkCommandUpstream.type_list_result:type_name -> link.TypeListRsp
	16, // 6: link.TypeGenRsp.pb:type_name -> link.TypeGenRsp.PbEntry
	17, // 7: link.AgentListRsp.agents:type_name -> link.AgentListRsp.AgentsEntry
	8,  // 8: link.Link.Link:input_type -> link.LinkCommandUpstream
	2,  // 9: link.Link.LinkCall:input_type -> link.LinkCallReq
	10, // 10: link.Link.TypeList:input_type -> link.TypeListReq
	12, // 11: link.Link.TypeGen:input_type -> link.TypeGenReq
	1,  // 12: link.Link.AgentList:input_type -> link.Empty
	4,  // 13: link.Link.Link:output_type -> link.LinkCommandDownstream
	3,  // 14: link.Link.LinkCall:output_type -> link.LinkCallRsp
	11, // 15: link.Link.TypeList:output_type -> link.TypeListRsp
	13, // 16: link.Link.TypeGen:output_type -> link.TypeGenRsp
	15, // 17: link.Link.AgentList:output_type -> link.AgentListRsp
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_link_proto_init() }
func file_link_proto_init() {
	if File_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_link_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_proto_goTypes,
		DependencyIndexes: file_link_proto_depIdxs,
		EnumInfos:         file_link_proto_enumTypes,
		MessageInfos:      file_link_proto_msgTypes,
	}.Build()
	File_link_proto = out.File
	file_link_proto_rawDesc = nil
	file_link_proto_goTypes = nil
	file_link_proto_depIdxs = nil
}
