// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shawn_define.proto

package shawn_define;

public final class ShawnDefine {
  private ShawnDefine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shawn_define.AddReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.shawn_define.V2 a = 1;</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>.shawn_define.V2 a = 1;</code>
     * @return The a.
     */
    shawn_define.ShawnDefine.V2 getA();
    /**
     * <code>.shawn_define.V2 a = 1;</code>
     */
    shawn_define.ShawnDefine.V2OrBuilder getAOrBuilder();

    /**
     * <code>.shawn_define.V2 b = 2;</code>
     * @return Whether the b field is set.
     */
    boolean hasB();
    /**
     * <code>.shawn_define.V2 b = 2;</code>
     * @return The b.
     */
    shawn_define.ShawnDefine.V2 getB();
    /**
     * <code>.shawn_define.V2 b = 2;</code>
     */
    shawn_define.ShawnDefine.V2OrBuilder getBOrBuilder();

    /**
     * <code>repeated int64 c = 3;</code>
     * @return A list containing the c.
     */
    java.util.List<java.lang.Long> getCList();
    /**
     * <code>repeated int64 c = 3;</code>
     * @return The count of c.
     */
    int getCCount();
    /**
     * <code>repeated int64 c = 3;</code>
     * @param index The index of the element to return.
     * @return The c at the given index.
     */
    long getC(int index);

    /**
     * <code>double d = 4;</code>
     * @return The d.
     */
    double getD();

    /**
     * <code>repeated double e = 5;</code>
     * @return A list containing the e.
     */
    java.util.List<java.lang.Double> getEList();
    /**
     * <code>repeated double e = 5;</code>
     * @return The count of e.
     */
    int getECount();
    /**
     * <code>repeated double e = 5;</code>
     * @param index The index of the element to return.
     * @return The e at the given index.
     */
    double getE(int index);
  }
  /**
   * Protobuf type {@code shawn_define.AddReq}
   */
  public static final class AddReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shawn_define.AddReq)
      AddReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddReq.newBuilder() to construct.
    private AddReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddReq() {
      c_ = emptyLongList();
      e_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return shawn_define.ShawnDefine.internal_static_shawn_define_AddReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return shawn_define.ShawnDefine.internal_static_shawn_define_AddReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              shawn_define.ShawnDefine.AddReq.class, shawn_define.ShawnDefine.AddReq.Builder.class);
    }

    private int bitField0_;
    public static final int A_FIELD_NUMBER = 1;
    private shawn_define.ShawnDefine.V2 a_;
    /**
     * <code>.shawn_define.V2 a = 1;</code>
     * @return Whether the a field is set.
     */
    @java.lang.Override
    public boolean hasA() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shawn_define.V2 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public shawn_define.ShawnDefine.V2 getA() {
      return a_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : a_;
    }
    /**
     * <code>.shawn_define.V2 a = 1;</code>
     */
    @java.lang.Override
    public shawn_define.ShawnDefine.V2OrBuilder getAOrBuilder() {
      return a_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private shawn_define.ShawnDefine.V2 b_;
    /**
     * <code>.shawn_define.V2 b = 2;</code>
     * @return Whether the b field is set.
     */
    @java.lang.Override
    public boolean hasB() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.shawn_define.V2 b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public shawn_define.ShawnDefine.V2 getB() {
      return b_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : b_;
    }
    /**
     * <code>.shawn_define.V2 b = 2;</code>
     */
    @java.lang.Override
    public shawn_define.ShawnDefine.V2OrBuilder getBOrBuilder() {
      return b_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : b_;
    }

    public static final int C_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList c_ =
        emptyLongList();
    /**
     * <code>repeated int64 c = 3;</code>
     * @return A list containing the c.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getCList() {
      return c_;
    }
    /**
     * <code>repeated int64 c = 3;</code>
     * @return The count of c.
     */
    public int getCCount() {
      return c_.size();
    }
    /**
     * <code>repeated int64 c = 3;</code>
     * @param index The index of the element to return.
     * @return The c at the given index.
     */
    public long getC(int index) {
      return c_.getLong(index);
    }
    private int cMemoizedSerializedSize = -1;

    public static final int D_FIELD_NUMBER = 4;
    private double d_ = 0D;
    /**
     * <code>double d = 4;</code>
     * @return The d.
     */
    @java.lang.Override
    public double getD() {
      return d_;
    }

    public static final int E_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.DoubleList e_ =
        emptyDoubleList();
    /**
     * <code>repeated double e = 5;</code>
     * @return A list containing the e.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getEList() {
      return e_;
    }
    /**
     * <code>repeated double e = 5;</code>
     * @return The count of e.
     */
    public int getECount() {
      return e_.size();
    }
    /**
     * <code>repeated double e = 5;</code>
     * @param index The index of the element to return.
     * @return The e at the given index.
     */
    public double getE(int index) {
      return e_.getDouble(index);
    }
    private int eMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getA());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getB());
      }
      if (getCList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(cMemoizedSerializedSize);
      }
      for (int i = 0; i < c_.size(); i++) {
        output.writeInt64NoTag(c_.getLong(i));
      }
      if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
        output.writeDouble(4, d_);
      }
      if (getEList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(eMemoizedSerializedSize);
      }
      for (int i = 0; i < e_.size(); i++) {
        output.writeDoubleNoTag(e_.getDouble(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getA());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getB());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < c_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(c_.getLong(i));
        }
        size += dataSize;
        if (!getCList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cMemoizedSerializedSize = dataSize;
      }
      if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, d_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getEList().size();
        size += dataSize;
        if (!getEList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        eMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof shawn_define.ShawnDefine.AddReq)) {
        return super.equals(obj);
      }
      shawn_define.ShawnDefine.AddReq other = (shawn_define.ShawnDefine.AddReq) obj;

      if (hasA() != other.hasA()) return false;
      if (hasA()) {
        if (!getA()
            .equals(other.getA())) return false;
      }
      if (hasB() != other.hasB()) return false;
      if (hasB()) {
        if (!getB()
            .equals(other.getB())) return false;
      }
      if (!getCList()
          .equals(other.getCList())) return false;
      if (java.lang.Double.doubleToLongBits(getD())
          != java.lang.Double.doubleToLongBits(
              other.getD())) return false;
      if (!getEList()
          .equals(other.getEList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasA()) {
        hash = (37 * hash) + A_FIELD_NUMBER;
        hash = (53 * hash) + getA().hashCode();
      }
      if (hasB()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB().hashCode();
      }
      if (getCCount() > 0) {
        hash = (37 * hash) + C_FIELD_NUMBER;
        hash = (53 * hash) + getCList().hashCode();
      }
      hash = (37 * hash) + D_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getD()));
      if (getECount() > 0) {
        hash = (37 * hash) + E_FIELD_NUMBER;
        hash = (53 * hash) + getEList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static shawn_define.ShawnDefine.AddReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static shawn_define.ShawnDefine.AddReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static shawn_define.ShawnDefine.AddReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shawn_define.ShawnDefine.AddReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(shawn_define.ShawnDefine.AddReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shawn_define.AddReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shawn_define.AddReq)
        shawn_define.ShawnDefine.AddReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_AddReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_AddReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                shawn_define.ShawnDefine.AddReq.class, shawn_define.ShawnDefine.AddReq.Builder.class);
      }

      // Construct using shawn_define.ShawnDefine.AddReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAFieldBuilder();
          getBFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = null;
        if (aBuilder_ != null) {
          aBuilder_.dispose();
          aBuilder_ = null;
        }
        b_ = null;
        if (bBuilder_ != null) {
          bBuilder_.dispose();
          bBuilder_ = null;
        }
        c_ = emptyLongList();
        d_ = 0D;
        e_ = emptyDoubleList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_AddReq_descriptor;
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.AddReq getDefaultInstanceForType() {
        return shawn_define.ShawnDefine.AddReq.getDefaultInstance();
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.AddReq build() {
        shawn_define.ShawnDefine.AddReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.AddReq buildPartial() {
        shawn_define.ShawnDefine.AddReq result = new shawn_define.ShawnDefine.AddReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(shawn_define.ShawnDefine.AddReq result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = aBuilder_ == null
              ? a_
              : aBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.b_ = bBuilder_ == null
              ? b_
              : bBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          c_.makeImmutable();
          result.c_ = c_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.d_ = d_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          e_.makeImmutable();
          result.e_ = e_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof shawn_define.ShawnDefine.AddReq) {
          return mergeFrom((shawn_define.ShawnDefine.AddReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(shawn_define.ShawnDefine.AddReq other) {
        if (other == shawn_define.ShawnDefine.AddReq.getDefaultInstance()) return this;
        if (other.hasA()) {
          mergeA(other.getA());
        }
        if (other.hasB()) {
          mergeB(other.getB());
        }
        if (!other.c_.isEmpty()) {
          if (c_.isEmpty()) {
            c_ = other.c_;
            c_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureCIsMutable();
            c_.addAll(other.c_);
          }
          onChanged();
        }
        if (other.getD() != 0D) {
          setD(other.getD());
        }
        if (!other.e_.isEmpty()) {
          if (e_.isEmpty()) {
            e_ = other.e_;
            e_.makeImmutable();
            bitField0_ |= 0x00000010;
          } else {
            ensureEIsMutable();
            e_.addAll(other.e_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getAFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getBFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                long v = input.readInt64();
                ensureCIsMutable();
                c_.addLong(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureCIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  c_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 33: {
                d_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                double v = input.readDouble();
                ensureEIsMutable();
                e_.addDouble(v);
                break;
              } // case 41
              case 42: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureEIsMutable(alloc / 8);
                while (input.getBytesUntilLimit() > 0) {
                  e_.addDouble(input.readDouble());
                }
                input.popLimit(limit);
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private shawn_define.ShawnDefine.V2 a_;
      private com.google.protobuf.SingleFieldBuilderV3<
          shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder> aBuilder_;
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       * @return Whether the a field is set.
       */
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       * @return The a.
       */
      public shawn_define.ShawnDefine.V2 getA() {
        if (aBuilder_ == null) {
          return a_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : a_;
        } else {
          return aBuilder_.getMessage();
        }
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      public Builder setA(shawn_define.ShawnDefine.V2 value) {
        if (aBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          a_ = value;
        } else {
          aBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      public Builder setA(
          shawn_define.ShawnDefine.V2.Builder builderForValue) {
        if (aBuilder_ == null) {
          a_ = builderForValue.build();
        } else {
          aBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      public Builder mergeA(shawn_define.ShawnDefine.V2 value) {
        if (aBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            a_ != null &&
            a_ != shawn_define.ShawnDefine.V2.getDefaultInstance()) {
            getABuilder().mergeFrom(value);
          } else {
            a_ = value;
          }
        } else {
          aBuilder_.mergeFrom(value);
        }
        if (a_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = null;
        if (aBuilder_ != null) {
          aBuilder_.dispose();
          aBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      public shawn_define.ShawnDefine.V2.Builder getABuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAFieldBuilder().getBuilder();
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      public shawn_define.ShawnDefine.V2OrBuilder getAOrBuilder() {
        if (aBuilder_ != null) {
          return aBuilder_.getMessageOrBuilder();
        } else {
          return a_ == null ?
              shawn_define.ShawnDefine.V2.getDefaultInstance() : a_;
        }
      }
      /**
       * <code>.shawn_define.V2 a = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder> 
          getAFieldBuilder() {
        if (aBuilder_ == null) {
          aBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder>(
                  getA(),
                  getParentForChildren(),
                  isClean());
          a_ = null;
        }
        return aBuilder_;
      }

      private shawn_define.ShawnDefine.V2 b_;
      private com.google.protobuf.SingleFieldBuilderV3<
          shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder> bBuilder_;
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       * @return Whether the b field is set.
       */
      public boolean hasB() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       * @return The b.
       */
      public shawn_define.ShawnDefine.V2 getB() {
        if (bBuilder_ == null) {
          return b_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : b_;
        } else {
          return bBuilder_.getMessage();
        }
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      public Builder setB(shawn_define.ShawnDefine.V2 value) {
        if (bBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          b_ = value;
        } else {
          bBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      public Builder setB(
          shawn_define.ShawnDefine.V2.Builder builderForValue) {
        if (bBuilder_ == null) {
          b_ = builderForValue.build();
        } else {
          bBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      public Builder mergeB(shawn_define.ShawnDefine.V2 value) {
        if (bBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            b_ != null &&
            b_ != shawn_define.ShawnDefine.V2.getDefaultInstance()) {
            getBBuilder().mergeFrom(value);
          } else {
            b_ = value;
          }
        } else {
          bBuilder_.mergeFrom(value);
        }
        if (b_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = null;
        if (bBuilder_ != null) {
          bBuilder_.dispose();
          bBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      public shawn_define.ShawnDefine.V2.Builder getBBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBFieldBuilder().getBuilder();
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      public shawn_define.ShawnDefine.V2OrBuilder getBOrBuilder() {
        if (bBuilder_ != null) {
          return bBuilder_.getMessageOrBuilder();
        } else {
          return b_ == null ?
              shawn_define.ShawnDefine.V2.getDefaultInstance() : b_;
        }
      }
      /**
       * <code>.shawn_define.V2 b = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder> 
          getBFieldBuilder() {
        if (bBuilder_ == null) {
          bBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder>(
                  getB(),
                  getParentForChildren(),
                  isClean());
          b_ = null;
        }
        return bBuilder_;
      }

      private com.google.protobuf.Internal.LongList c_ = emptyLongList();
      private void ensureCIsMutable() {
        if (!c_.isModifiable()) {
          c_ = makeMutableCopy(c_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @return A list containing the c.
       */
      public java.util.List<java.lang.Long>
          getCList() {
        c_.makeImmutable();
        return c_;
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @return The count of c.
       */
      public int getCCount() {
        return c_.size();
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @param index The index of the element to return.
       * @return The c at the given index.
       */
      public long getC(int index) {
        return c_.getLong(index);
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @param index The index to set the value at.
       * @param value The c to set.
       * @return This builder for chaining.
       */
      public Builder setC(
          int index, long value) {

        ensureCIsMutable();
        c_.setLong(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @param value The c to add.
       * @return This builder for chaining.
       */
      public Builder addC(long value) {

        ensureCIsMutable();
        c_.addLong(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @param values The c to add.
       * @return This builder for chaining.
       */
      public Builder addAllC(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureCIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, c_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 c = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearC() {
        c_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private double d_ ;
      /**
       * <code>double d = 4;</code>
       * @return The d.
       */
      @java.lang.Override
      public double getD() {
        return d_;
      }
      /**
       * <code>double d = 4;</code>
       * @param value The d to set.
       * @return This builder for chaining.
       */
      public Builder setD(double value) {

        d_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double d = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000008);
        d_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList e_ = emptyDoubleList();
      private void ensureEIsMutable() {
        if (!e_.isModifiable()) {
          e_ = makeMutableCopy(e_);
        }
        bitField0_ |= 0x00000010;
      }
      private void ensureEIsMutable(int capacity) {
        if (!e_.isModifiable()) {
          e_ = makeMutableCopy(e_, capacity);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated double e = 5;</code>
       * @return A list containing the e.
       */
      public java.util.List<java.lang.Double>
          getEList() {
        e_.makeImmutable();
        return e_;
      }
      /**
       * <code>repeated double e = 5;</code>
       * @return The count of e.
       */
      public int getECount() {
        return e_.size();
      }
      /**
       * <code>repeated double e = 5;</code>
       * @param index The index of the element to return.
       * @return The e at the given index.
       */
      public double getE(int index) {
        return e_.getDouble(index);
      }
      /**
       * <code>repeated double e = 5;</code>
       * @param index The index to set the value at.
       * @param value The e to set.
       * @return This builder for chaining.
       */
      public Builder setE(
          int index, double value) {

        ensureEIsMutable();
        e_.setDouble(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double e = 5;</code>
       * @param value The e to add.
       * @return This builder for chaining.
       */
      public Builder addE(double value) {

        ensureEIsMutable();
        e_.addDouble(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double e = 5;</code>
       * @param values The e to add.
       * @return This builder for chaining.
       */
      public Builder addAllE(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureEIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, e_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double e = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearE() {
        e_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shawn_define.AddReq)
    }

    // @@protoc_insertion_point(class_scope:shawn_define.AddReq)
    private static final shawn_define.ShawnDefine.AddReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new shawn_define.ShawnDefine.AddReq();
    }

    public static shawn_define.ShawnDefine.AddReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddReq>
        PARSER = new com.google.protobuf.AbstractParser<AddReq>() {
      @java.lang.Override
      public AddReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public shawn_define.ShawnDefine.AddReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface V2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:shawn_define.V2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 a = 1;</code>
     * @return The a.
     */
    long getA();

    /**
     * <code>int64 b = 2;</code>
     * @return The b.
     */
    long getB();
  }
  /**
   * Protobuf type {@code shawn_define.V2}
   */
  public static final class V2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shawn_define.V2)
      V2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use V2.newBuilder() to construct.
    private V2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private V2() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new V2();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return shawn_define.ShawnDefine.internal_static_shawn_define_V2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return shawn_define.ShawnDefine.internal_static_shawn_define_V2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              shawn_define.ShawnDefine.V2.class, shawn_define.ShawnDefine.V2.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private long a_ = 0L;
    /**
     * <code>int64 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public long getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private long b_ = 0L;
    /**
     * <code>int64 b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public long getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0L) {
        output.writeInt64(1, a_);
      }
      if (b_ != 0L) {
        output.writeInt64(2, b_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, a_);
      }
      if (b_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, b_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof shawn_define.ShawnDefine.V2)) {
        return super.equals(obj);
      }
      shawn_define.ShawnDefine.V2 other = (shawn_define.ShawnDefine.V2) obj;

      if (getA()
          != other.getA()) return false;
      if (getB()
          != other.getB()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getA());
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getB());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static shawn_define.ShawnDefine.V2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static shawn_define.ShawnDefine.V2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static shawn_define.ShawnDefine.V2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shawn_define.ShawnDefine.V2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(shawn_define.ShawnDefine.V2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shawn_define.V2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shawn_define.V2)
        shawn_define.ShawnDefine.V2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_V2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_V2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                shawn_define.ShawnDefine.V2.class, shawn_define.ShawnDefine.V2.Builder.class);
      }

      // Construct using shawn_define.ShawnDefine.V2.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = 0L;
        b_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_V2_descriptor;
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.V2 getDefaultInstanceForType() {
        return shawn_define.ShawnDefine.V2.getDefaultInstance();
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.V2 build() {
        shawn_define.ShawnDefine.V2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.V2 buildPartial() {
        shawn_define.ShawnDefine.V2 result = new shawn_define.ShawnDefine.V2(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(shawn_define.ShawnDefine.V2 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = a_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.b_ = b_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof shawn_define.ShawnDefine.V2) {
          return mergeFrom((shawn_define.ShawnDefine.V2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(shawn_define.ShawnDefine.V2 other) {
        if (other == shawn_define.ShawnDefine.V2.getDefaultInstance()) return this;
        if (other.getA() != 0L) {
          setA(other.getA());
        }
        if (other.getB() != 0L) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                a_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                b_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long a_ ;
      /**
       * <code>int64 a = 1;</code>
       * @return The a.
       */
      @java.lang.Override
      public long getA() {
        return a_;
      }
      /**
       * <code>int64 a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(long value) {

        a_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0L;
        onChanged();
        return this;
      }

      private long b_ ;
      /**
       * <code>int64 b = 2;</code>
       * @return The b.
       */
      @java.lang.Override
      public long getB() {
        return b_;
      }
      /**
       * <code>int64 b = 2;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(long value) {

        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 b = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shawn_define.V2)
    }

    // @@protoc_insertion_point(class_scope:shawn_define.V2)
    private static final shawn_define.ShawnDefine.V2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new shawn_define.ShawnDefine.V2();
    }

    public static shawn_define.ShawnDefine.V2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<V2>
        PARSER = new com.google.protobuf.AbstractParser<V2>() {
      @java.lang.Override
      public V2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<V2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<V2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public shawn_define.ShawnDefine.V2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:shawn_define.AddRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.shawn_define.V2 res = 1;</code>
     * @return Whether the res field is set.
     */
    boolean hasRes();
    /**
     * <code>.shawn_define.V2 res = 1;</code>
     * @return The res.
     */
    shawn_define.ShawnDefine.V2 getRes();
    /**
     * <code>.shawn_define.V2 res = 1;</code>
     */
    shawn_define.ShawnDefine.V2OrBuilder getResOrBuilder();

    /**
     * <code>repeated int64 c = 2;</code>
     * @return A list containing the c.
     */
    java.util.List<java.lang.Long> getCList();
    /**
     * <code>repeated int64 c = 2;</code>
     * @return The count of c.
     */
    int getCCount();
    /**
     * <code>repeated int64 c = 2;</code>
     * @param index The index of the element to return.
     * @return The c at the given index.
     */
    long getC(int index);

    /**
     * <code>double d = 3;</code>
     * @return The d.
     */
    double getD();

    /**
     * <code>repeated double e = 4;</code>
     * @return A list containing the e.
     */
    java.util.List<java.lang.Double> getEList();
    /**
     * <code>repeated double e = 4;</code>
     * @return The count of e.
     */
    int getECount();
    /**
     * <code>repeated double e = 4;</code>
     * @param index The index of the element to return.
     * @return The e at the given index.
     */
    double getE(int index);
  }
  /**
   * Protobuf type {@code shawn_define.AddRsp}
   */
  public static final class AddRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:shawn_define.AddRsp)
      AddRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddRsp.newBuilder() to construct.
    private AddRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddRsp() {
      c_ = emptyLongList();
      e_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddRsp();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return shawn_define.ShawnDefine.internal_static_shawn_define_AddRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return shawn_define.ShawnDefine.internal_static_shawn_define_AddRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              shawn_define.ShawnDefine.AddRsp.class, shawn_define.ShawnDefine.AddRsp.Builder.class);
    }

    private int bitField0_;
    public static final int RES_FIELD_NUMBER = 1;
    private shawn_define.ShawnDefine.V2 res_;
    /**
     * <code>.shawn_define.V2 res = 1;</code>
     * @return Whether the res field is set.
     */
    @java.lang.Override
    public boolean hasRes() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.shawn_define.V2 res = 1;</code>
     * @return The res.
     */
    @java.lang.Override
    public shawn_define.ShawnDefine.V2 getRes() {
      return res_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : res_;
    }
    /**
     * <code>.shawn_define.V2 res = 1;</code>
     */
    @java.lang.Override
    public shawn_define.ShawnDefine.V2OrBuilder getResOrBuilder() {
      return res_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : res_;
    }

    public static final int C_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList c_ =
        emptyLongList();
    /**
     * <code>repeated int64 c = 2;</code>
     * @return A list containing the c.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getCList() {
      return c_;
    }
    /**
     * <code>repeated int64 c = 2;</code>
     * @return The count of c.
     */
    public int getCCount() {
      return c_.size();
    }
    /**
     * <code>repeated int64 c = 2;</code>
     * @param index The index of the element to return.
     * @return The c at the given index.
     */
    public long getC(int index) {
      return c_.getLong(index);
    }
    private int cMemoizedSerializedSize = -1;

    public static final int D_FIELD_NUMBER = 3;
    private double d_ = 0D;
    /**
     * <code>double d = 3;</code>
     * @return The d.
     */
    @java.lang.Override
    public double getD() {
      return d_;
    }

    public static final int E_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.DoubleList e_ =
        emptyDoubleList();
    /**
     * <code>repeated double e = 4;</code>
     * @return A list containing the e.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getEList() {
      return e_;
    }
    /**
     * <code>repeated double e = 4;</code>
     * @return The count of e.
     */
    public int getECount() {
      return e_.size();
    }
    /**
     * <code>repeated double e = 4;</code>
     * @param index The index of the element to return.
     * @return The e at the given index.
     */
    public double getE(int index) {
      return e_.getDouble(index);
    }
    private int eMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getRes());
      }
      if (getCList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(cMemoizedSerializedSize);
      }
      for (int i = 0; i < c_.size(); i++) {
        output.writeInt64NoTag(c_.getLong(i));
      }
      if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
        output.writeDouble(3, d_);
      }
      if (getEList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(eMemoizedSerializedSize);
      }
      for (int i = 0; i < e_.size(); i++) {
        output.writeDoubleNoTag(e_.getDouble(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < c_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(c_.getLong(i));
        }
        size += dataSize;
        if (!getCList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cMemoizedSerializedSize = dataSize;
      }
      if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, d_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getEList().size();
        size += dataSize;
        if (!getEList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        eMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof shawn_define.ShawnDefine.AddRsp)) {
        return super.equals(obj);
      }
      shawn_define.ShawnDefine.AddRsp other = (shawn_define.ShawnDefine.AddRsp) obj;

      if (hasRes() != other.hasRes()) return false;
      if (hasRes()) {
        if (!getRes()
            .equals(other.getRes())) return false;
      }
      if (!getCList()
          .equals(other.getCList())) return false;
      if (java.lang.Double.doubleToLongBits(getD())
          != java.lang.Double.doubleToLongBits(
              other.getD())) return false;
      if (!getEList()
          .equals(other.getEList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRes()) {
        hash = (37 * hash) + RES_FIELD_NUMBER;
        hash = (53 * hash) + getRes().hashCode();
      }
      if (getCCount() > 0) {
        hash = (37 * hash) + C_FIELD_NUMBER;
        hash = (53 * hash) + getCList().hashCode();
      }
      hash = (37 * hash) + D_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getD()));
      if (getECount() > 0) {
        hash = (37 * hash) + E_FIELD_NUMBER;
        hash = (53 * hash) + getEList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static shawn_define.ShawnDefine.AddRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static shawn_define.ShawnDefine.AddRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static shawn_define.ShawnDefine.AddRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(shawn_define.ShawnDefine.AddRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code shawn_define.AddRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:shawn_define.AddRsp)
        shawn_define.ShawnDefine.AddRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_AddRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_AddRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                shawn_define.ShawnDefine.AddRsp.class, shawn_define.ShawnDefine.AddRsp.Builder.class);
      }

      // Construct using shawn_define.ShawnDefine.AddRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        res_ = null;
        if (resBuilder_ != null) {
          resBuilder_.dispose();
          resBuilder_ = null;
        }
        c_ = emptyLongList();
        d_ = 0D;
        e_ = emptyDoubleList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return shawn_define.ShawnDefine.internal_static_shawn_define_AddRsp_descriptor;
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.AddRsp getDefaultInstanceForType() {
        return shawn_define.ShawnDefine.AddRsp.getDefaultInstance();
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.AddRsp build() {
        shawn_define.ShawnDefine.AddRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public shawn_define.ShawnDefine.AddRsp buildPartial() {
        shawn_define.ShawnDefine.AddRsp result = new shawn_define.ShawnDefine.AddRsp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(shawn_define.ShawnDefine.AddRsp result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.res_ = resBuilder_ == null
              ? res_
              : resBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          c_.makeImmutable();
          result.c_ = c_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.d_ = d_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          e_.makeImmutable();
          result.e_ = e_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof shawn_define.ShawnDefine.AddRsp) {
          return mergeFrom((shawn_define.ShawnDefine.AddRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(shawn_define.ShawnDefine.AddRsp other) {
        if (other == shawn_define.ShawnDefine.AddRsp.getDefaultInstance()) return this;
        if (other.hasRes()) {
          mergeRes(other.getRes());
        }
        if (!other.c_.isEmpty()) {
          if (c_.isEmpty()) {
            c_ = other.c_;
            c_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureCIsMutable();
            c_.addAll(other.c_);
          }
          onChanged();
        }
        if (other.getD() != 0D) {
          setD(other.getD());
        }
        if (!other.e_.isEmpty()) {
          if (e_.isEmpty()) {
            e_ = other.e_;
            e_.makeImmutable();
            bitField0_ |= 0x00000008;
          } else {
            ensureEIsMutable();
            e_.addAll(other.e_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getResFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                long v = input.readInt64();
                ensureCIsMutable();
                c_.addLong(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureCIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  c_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 18
              case 25: {
                d_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                double v = input.readDouble();
                ensureEIsMutable();
                e_.addDouble(v);
                break;
              } // case 33
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureEIsMutable(alloc / 8);
                while (input.getBytesUntilLimit() > 0) {
                  e_.addDouble(input.readDouble());
                }
                input.popLimit(limit);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private shawn_define.ShawnDefine.V2 res_;
      private com.google.protobuf.SingleFieldBuilderV3<
          shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder> resBuilder_;
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       * @return Whether the res field is set.
       */
      public boolean hasRes() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       * @return The res.
       */
      public shawn_define.ShawnDefine.V2 getRes() {
        if (resBuilder_ == null) {
          return res_ == null ? shawn_define.ShawnDefine.V2.getDefaultInstance() : res_;
        } else {
          return resBuilder_.getMessage();
        }
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      public Builder setRes(shawn_define.ShawnDefine.V2 value) {
        if (resBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          res_ = value;
        } else {
          resBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      public Builder setRes(
          shawn_define.ShawnDefine.V2.Builder builderForValue) {
        if (resBuilder_ == null) {
          res_ = builderForValue.build();
        } else {
          resBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      public Builder mergeRes(shawn_define.ShawnDefine.V2 value) {
        if (resBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            res_ != null &&
            res_ != shawn_define.ShawnDefine.V2.getDefaultInstance()) {
            getResBuilder().mergeFrom(value);
          } else {
            res_ = value;
          }
        } else {
          resBuilder_.mergeFrom(value);
        }
        if (res_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      public Builder clearRes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        res_ = null;
        if (resBuilder_ != null) {
          resBuilder_.dispose();
          resBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      public shawn_define.ShawnDefine.V2.Builder getResBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResFieldBuilder().getBuilder();
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      public shawn_define.ShawnDefine.V2OrBuilder getResOrBuilder() {
        if (resBuilder_ != null) {
          return resBuilder_.getMessageOrBuilder();
        } else {
          return res_ == null ?
              shawn_define.ShawnDefine.V2.getDefaultInstance() : res_;
        }
      }
      /**
       * <code>.shawn_define.V2 res = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder> 
          getResFieldBuilder() {
        if (resBuilder_ == null) {
          resBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              shawn_define.ShawnDefine.V2, shawn_define.ShawnDefine.V2.Builder, shawn_define.ShawnDefine.V2OrBuilder>(
                  getRes(),
                  getParentForChildren(),
                  isClean());
          res_ = null;
        }
        return resBuilder_;
      }

      private com.google.protobuf.Internal.LongList c_ = emptyLongList();
      private void ensureCIsMutable() {
        if (!c_.isModifiable()) {
          c_ = makeMutableCopy(c_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @return A list containing the c.
       */
      public java.util.List<java.lang.Long>
          getCList() {
        c_.makeImmutable();
        return c_;
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @return The count of c.
       */
      public int getCCount() {
        return c_.size();
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @param index The index of the element to return.
       * @return The c at the given index.
       */
      public long getC(int index) {
        return c_.getLong(index);
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @param index The index to set the value at.
       * @param value The c to set.
       * @return This builder for chaining.
       */
      public Builder setC(
          int index, long value) {

        ensureCIsMutable();
        c_.setLong(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @param value The c to add.
       * @return This builder for chaining.
       */
      public Builder addC(long value) {

        ensureCIsMutable();
        c_.addLong(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @param values The c to add.
       * @return This builder for chaining.
       */
      public Builder addAllC(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureCIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, c_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 c = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearC() {
        c_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private double d_ ;
      /**
       * <code>double d = 3;</code>
       * @return The d.
       */
      @java.lang.Override
      public double getD() {
        return d_;
      }
      /**
       * <code>double d = 3;</code>
       * @param value The d to set.
       * @return This builder for chaining.
       */
      public Builder setD(double value) {

        d_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double d = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000004);
        d_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList e_ = emptyDoubleList();
      private void ensureEIsMutable() {
        if (!e_.isModifiable()) {
          e_ = makeMutableCopy(e_);
        }
        bitField0_ |= 0x00000008;
      }
      private void ensureEIsMutable(int capacity) {
        if (!e_.isModifiable()) {
          e_ = makeMutableCopy(e_, capacity);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated double e = 4;</code>
       * @return A list containing the e.
       */
      public java.util.List<java.lang.Double>
          getEList() {
        e_.makeImmutable();
        return e_;
      }
      /**
       * <code>repeated double e = 4;</code>
       * @return The count of e.
       */
      public int getECount() {
        return e_.size();
      }
      /**
       * <code>repeated double e = 4;</code>
       * @param index The index of the element to return.
       * @return The e at the given index.
       */
      public double getE(int index) {
        return e_.getDouble(index);
      }
      /**
       * <code>repeated double e = 4;</code>
       * @param index The index to set the value at.
       * @param value The e to set.
       * @return This builder for chaining.
       */
      public Builder setE(
          int index, double value) {

        ensureEIsMutable();
        e_.setDouble(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double e = 4;</code>
       * @param value The e to add.
       * @return This builder for chaining.
       */
      public Builder addE(double value) {

        ensureEIsMutable();
        e_.addDouble(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double e = 4;</code>
       * @param values The e to add.
       * @return This builder for chaining.
       */
      public Builder addAllE(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureEIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, e_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double e = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearE() {
        e_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:shawn_define.AddRsp)
    }

    // @@protoc_insertion_point(class_scope:shawn_define.AddRsp)
    private static final shawn_define.ShawnDefine.AddRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new shawn_define.ShawnDefine.AddRsp();
    }

    public static shawn_define.ShawnDefine.AddRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddRsp>
        PARSER = new com.google.protobuf.AbstractParser<AddRsp>() {
      @java.lang.Override
      public AddRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public shawn_define.ShawnDefine.AddRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shawn_define_AddReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shawn_define_AddReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shawn_define_V2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shawn_define_V2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_shawn_define_AddRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_shawn_define_AddRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022shawn_define.proto\022\014shawn_define\"c\n\006Ad" +
      "dReq\022\033\n\001a\030\001 \001(\0132\020.shawn_define.V2\022\033\n\001b\030\002" +
      " \001(\0132\020.shawn_define.V2\022\t\n\001c\030\003 \003(\003\022\t\n\001d\030\004" +
      " \001(\001\022\t\n\001e\030\005 \003(\001\"\032\n\002V2\022\t\n\001a\030\001 \001(\003\022\t\n\001b\030\002 " +
      "\001(\003\"H\n\006AddRsp\022\035\n\003res\030\001 \001(\0132\020.shawn_defin" +
      "e.V2\022\t\n\001c\030\002 \003(\003\022\t\n\001d\030\003 \001(\001\022\t\n\001e\030\004 \003(\001B\006Z" +
      "\004./pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_shawn_define_AddReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_shawn_define_AddReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shawn_define_AddReq_descriptor,
        new java.lang.String[] { "A", "B", "C", "D", "E", });
    internal_static_shawn_define_V2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_shawn_define_V2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shawn_define_V2_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_shawn_define_AddRsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_shawn_define_AddRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_shawn_define_AddRsp_descriptor,
        new java.lang.String[] { "Res", "C", "D", "E", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
