// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: main.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_PublishTopicMsg_FullMethodName          = "/Api/PublishTopicMsg"
	Api_PublishTopicChatter_FullMethodName      = "/Api/PublishTopicChatter"
	Api_CallServiceAddTwoIntsSrv_FullMethodName = "/Api/CallServiceAdd_two_ints_srv"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	// topic: /msg
	PublishTopicMsg(ctx context.Context, in *Msg1, opts ...grpc.CallOption) (*Msg1, error)
	// topic: /chatter
	PublishTopicChatter(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
	// service: /add_two_ints_srv
	CallServiceAddTwoIntsSrv(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddRsp, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) PublishTopicMsg(ctx context.Context, in *Msg1, opts ...grpc.CallOption) (*Msg1, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Msg1)
	err := c.cc.Invoke(ctx, Api_PublishTopicMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) PublishTopicChatter(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(String)
	err := c.cc.Invoke(ctx, Api_PublishTopicChatter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CallServiceAddTwoIntsSrv(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRsp)
	err := c.cc.Invoke(ctx, Api_CallServiceAddTwoIntsSrv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	// topic: /msg
	PublishTopicMsg(context.Context, *Msg1) (*Msg1, error)
	// topic: /chatter
	PublishTopicChatter(context.Context, *String) (*String, error)
	// service: /add_two_ints_srv
	CallServiceAddTwoIntsSrv(context.Context, *AddReq) (*AddRsp, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) PublishTopicMsg(context.Context, *Msg1) (*Msg1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishTopicMsg not implemented")
}
func (UnimplementedApiServer) PublishTopicChatter(context.Context, *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishTopicChatter not implemented")
}
func (UnimplementedApiServer) CallServiceAddTwoIntsSrv(context.Context, *AddReq) (*AddRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallServiceAddTwoIntsSrv not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_PublishTopicMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PublishTopicMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_PublishTopicMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PublishTopicMsg(ctx, req.(*Msg1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_PublishTopicChatter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PublishTopicChatter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_PublishTopicChatter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PublishTopicChatter(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CallServiceAddTwoIntsSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CallServiceAddTwoIntsSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CallServiceAddTwoIntsSrv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CallServiceAddTwoIntsSrv(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishTopicMsg",
			Handler:    _Api_PublishTopicMsg_Handler,
		},
		{
			MethodName: "PublishTopicChatter",
			Handler:    _Api_PublishTopicChatter_Handler,
		},
		{
			MethodName: "CallServiceAdd_two_ints_srv",
			Handler:    _Api_CallServiceAddTwoIntsSrv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
