/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: main.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var pkg_b_pb = require('./pkg_b_pb.js')

var pkg_c_pb = require('./pkg_c_pb.js')

var rcl_interfaces_pb = require('./rcl_interfaces_pb.js')

var builtin_interfaces_pb = require('./builtin_interfaces_pb.js')

var shawn_define_pb = require('./shawn_define_pb.js')

var std_msgs_pb = require('./std_msgs_pb.js')

var pkg_d_pb = require('./pkg_d_pb.js')

var pkg_a_pb = require('./pkg_a_pb.js')
const proto = require('./main_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ApiClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ApiPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.ParameterEvent,
 *   !proto.rcl_interfaces.ParameterEvent>}
 */
const methodDescriptor_Api_PublishTopicParameter_events = new grpc.web.MethodDescriptor(
  '/Api/PublishTopicParameter_events',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.ParameterEvent,
  rcl_interfaces_pb.ParameterEvent,
  /**
   * @param {!proto.rcl_interfaces.ParameterEvent} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.ParameterEvent.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.ParameterEvent} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.ParameterEvent)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.ParameterEvent>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.publishTopicParameter_events =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/PublishTopicParameter_events',
      request,
      metadata || {},
      methodDescriptor_Api_PublishTopicParameter_events,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.ParameterEvent} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.ParameterEvent>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.publishTopicParameter_events =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/PublishTopicParameter_events',
      request,
      metadata || {},
      methodDescriptor_Api_PublishTopicParameter_events);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.Log,
 *   !proto.rcl_interfaces.Log>}
 */
const methodDescriptor_Api_PublishTopicRosout = new grpc.web.MethodDescriptor(
  '/Api/PublishTopicRosout',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.Log,
  rcl_interfaces_pb.Log,
  /**
   * @param {!proto.rcl_interfaces.Log} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.Log.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.Log} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.Log)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.Log>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.publishTopicRosout =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/PublishTopicRosout',
      request,
      metadata || {},
      methodDescriptor_Api_PublishTopicRosout,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.Log} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.Log>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.publishTopicRosout =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/PublishTopicRosout',
      request,
      metadata || {},
      methodDescriptor_Api_PublishTopicRosout);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.std_msgs.String,
 *   !proto.std_msgs.String>}
 */
const methodDescriptor_Api_PublishTopicChatter = new grpc.web.MethodDescriptor(
  '/Api/PublishTopicChatter',
  grpc.web.MethodType.UNARY,
  std_msgs_pb.String,
  std_msgs_pb.String,
  /**
   * @param {!proto.std_msgs.String} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  std_msgs_pb.String.deserializeBinary
);


/**
 * @param {!proto.std_msgs.String} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.std_msgs.String)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.std_msgs.String>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.publishTopicChatter =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/PublishTopicChatter',
      request,
      metadata || {},
      methodDescriptor_Api_PublishTopicChatter,
      callback);
};


/**
 * @param {!proto.std_msgs.String} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.std_msgs.String>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.publishTopicChatter =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/PublishTopicChatter',
      request,
      metadata || {},
      methodDescriptor_Api_PublishTopicChatter);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.DescribeParametersReq,
 *   !proto.rcl_interfaces.DescribeParametersRsp>}
 */
const methodDescriptor_Api_CallServiceListenerDescribe_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceListenerDescribe_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.DescribeParametersReq,
  rcl_interfaces_pb.DescribeParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.DescribeParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.DescribeParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.DescribeParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.DescribeParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.DescribeParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceListenerDescribe_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceListenerDescribe_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerDescribe_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.DescribeParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.DescribeParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceListenerDescribe_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceListenerDescribe_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerDescribe_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.GetParametersReq,
 *   !proto.rcl_interfaces.GetParametersRsp>}
 */
const methodDescriptor_Api_CallServiceListenerGet_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceListenerGet_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.GetParametersReq,
  rcl_interfaces_pb.GetParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.GetParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.GetParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.GetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.GetParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.GetParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceListenerGet_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceListenerGet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerGet_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.GetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.GetParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceListenerGet_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceListenerGet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerGet_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.SetParametersReq,
 *   !proto.rcl_interfaces.SetParametersRsp>}
 */
const methodDescriptor_Api_CallServiceService_server_02Set_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceService_server_02Set_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.SetParametersReq,
  rcl_interfaces_pb.SetParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.SetParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.SetParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.SetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.SetParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.SetParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceService_server_02Set_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceService_server_02Set_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Set_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.SetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.SetParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceService_server_02Set_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceService_server_02Set_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Set_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.GetParametersReq,
 *   !proto.rcl_interfaces.GetParametersRsp>}
 */
const methodDescriptor_Api_CallServiceService_server_02Get_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceService_server_02Get_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.GetParametersReq,
  rcl_interfaces_pb.GetParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.GetParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.GetParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.GetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.GetParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.GetParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceService_server_02Get_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceService_server_02Get_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Get_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.GetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.GetParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceService_server_02Get_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceService_server_02Get_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Get_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.GetParameterTypesReq,
 *   !proto.rcl_interfaces.GetParameterTypesRsp>}
 */
const methodDescriptor_Api_CallServiceService_server_02Get_parameter_types = new grpc.web.MethodDescriptor(
  '/Api/CallServiceService_server_02Get_parameter_types',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.GetParameterTypesReq,
  rcl_interfaces_pb.GetParameterTypesRsp,
  /**
   * @param {!proto.rcl_interfaces.GetParameterTypesReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.GetParameterTypesRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.GetParameterTypesReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.GetParameterTypesRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.GetParameterTypesRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceService_server_02Get_parameter_types =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceService_server_02Get_parameter_types',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Get_parameter_types,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.GetParameterTypesReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.GetParameterTypesRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceService_server_02Get_parameter_types =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceService_server_02Get_parameter_types',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Get_parameter_types);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.SetParametersAtomicallyReq,
 *   !proto.rcl_interfaces.SetParametersAtomicallyRsp>}
 */
const methodDescriptor_Api_CallServiceFoxglove_bridgeSet_parameters_atomically = new grpc.web.MethodDescriptor(
  '/Api/CallServiceFoxglove_bridgeSet_parameters_atomically',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.SetParametersAtomicallyReq,
  rcl_interfaces_pb.SetParametersAtomicallyRsp,
  /**
   * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.SetParametersAtomicallyRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.SetParametersAtomicallyRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.SetParametersAtomicallyRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceFoxglove_bridgeSet_parameters_atomically =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeSet_parameters_atomically',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeSet_parameters_atomically,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.SetParametersAtomicallyRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceFoxglove_bridgeSet_parameters_atomically =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeSet_parameters_atomically',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeSet_parameters_atomically);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.DescribeParametersReq,
 *   !proto.rcl_interfaces.DescribeParametersRsp>}
 */
const methodDescriptor_Api_CallServiceService_server_02Describe_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceService_server_02Describe_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.DescribeParametersReq,
  rcl_interfaces_pb.DescribeParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.DescribeParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.DescribeParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.DescribeParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.DescribeParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.DescribeParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceService_server_02Describe_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceService_server_02Describe_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Describe_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.DescribeParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.DescribeParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceService_server_02Describe_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceService_server_02Describe_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Describe_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.ListParametersReq,
 *   !proto.rcl_interfaces.ListParametersRsp>}
 */
const methodDescriptor_Api_CallServiceListenerList_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceListenerList_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.ListParametersReq,
  rcl_interfaces_pb.ListParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.ListParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.ListParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.ListParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.ListParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.ListParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceListenerList_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceListenerList_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerList_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.ListParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.ListParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceListenerList_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceListenerList_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerList_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.GetParameterTypesReq,
 *   !proto.rcl_interfaces.GetParameterTypesRsp>}
 */
const methodDescriptor_Api_CallServiceFoxglove_bridgeGet_parameter_types = new grpc.web.MethodDescriptor(
  '/Api/CallServiceFoxglove_bridgeGet_parameter_types',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.GetParameterTypesReq,
  rcl_interfaces_pb.GetParameterTypesRsp,
  /**
   * @param {!proto.rcl_interfaces.GetParameterTypesReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.GetParameterTypesRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.GetParameterTypesReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.GetParameterTypesRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.GetParameterTypesRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceFoxglove_bridgeGet_parameter_types =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeGet_parameter_types',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeGet_parameter_types,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.GetParameterTypesReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.GetParameterTypesRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceFoxglove_bridgeGet_parameter_types =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeGet_parameter_types',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeGet_parameter_types);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.shawn_define.AddReq,
 *   !proto.shawn_define.AddRsp>}
 */
const methodDescriptor_Api_CallServiceAdd_two_ints_srv = new grpc.web.MethodDescriptor(
  '/Api/CallServiceAdd_two_ints_srv',
  grpc.web.MethodType.UNARY,
  shawn_define_pb.AddReq,
  shawn_define_pb.AddRsp,
  /**
   * @param {!proto.shawn_define.AddReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  shawn_define_pb.AddRsp.deserializeBinary
);


/**
 * @param {!proto.shawn_define.AddReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.shawn_define.AddRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.shawn_define.AddRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceAdd_two_ints_srv =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceAdd_two_ints_srv',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceAdd_two_ints_srv,
      callback);
};


/**
 * @param {!proto.shawn_define.AddReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.shawn_define.AddRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceAdd_two_ints_srv =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceAdd_two_ints_srv',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceAdd_two_ints_srv);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pkg_d.GetPersonReq,
 *   !proto.pkg_d.GetPersonRsp>}
 */
const methodDescriptor_Api_CallServiceGet_person = new grpc.web.MethodDescriptor(
  '/Api/CallServiceGet_person',
  grpc.web.MethodType.UNARY,
  pkg_d_pb.GetPersonReq,
  pkg_d_pb.GetPersonRsp,
  /**
   * @param {!proto.pkg_d.GetPersonReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  pkg_d_pb.GetPersonRsp.deserializeBinary
);


/**
 * @param {!proto.pkg_d.GetPersonReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pkg_d.GetPersonRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pkg_d.GetPersonRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceGet_person =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceGet_person',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceGet_person,
      callback);
};


/**
 * @param {!proto.pkg_d.GetPersonReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pkg_d.GetPersonRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceGet_person =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceGet_person',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceGet_person);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.GetParameterTypesReq,
 *   !proto.rcl_interfaces.GetParameterTypesRsp>}
 */
const methodDescriptor_Api_CallServiceListenerGet_parameter_types = new grpc.web.MethodDescriptor(
  '/Api/CallServiceListenerGet_parameter_types',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.GetParameterTypesReq,
  rcl_interfaces_pb.GetParameterTypesRsp,
  /**
   * @param {!proto.rcl_interfaces.GetParameterTypesReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.GetParameterTypesRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.GetParameterTypesReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.GetParameterTypesRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.GetParameterTypesRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceListenerGet_parameter_types =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceListenerGet_parameter_types',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerGet_parameter_types,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.GetParameterTypesReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.GetParameterTypesRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceListenerGet_parameter_types =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceListenerGet_parameter_types',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerGet_parameter_types);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.ListParametersReq,
 *   !proto.rcl_interfaces.ListParametersRsp>}
 */
const methodDescriptor_Api_CallServiceFoxglove_bridgeList_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceFoxglove_bridgeList_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.ListParametersReq,
  rcl_interfaces_pb.ListParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.ListParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.ListParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.ListParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.ListParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.ListParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceFoxglove_bridgeList_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeList_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeList_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.ListParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.ListParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceFoxglove_bridgeList_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeList_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeList_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.SetParametersAtomicallyReq,
 *   !proto.rcl_interfaces.SetParametersAtomicallyRsp>}
 */
const methodDescriptor_Api_CallServiceListenerSet_parameters_atomically = new grpc.web.MethodDescriptor(
  '/Api/CallServiceListenerSet_parameters_atomically',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.SetParametersAtomicallyReq,
  rcl_interfaces_pb.SetParametersAtomicallyRsp,
  /**
   * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.SetParametersAtomicallyRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.SetParametersAtomicallyRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.SetParametersAtomicallyRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceListenerSet_parameters_atomically =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceListenerSet_parameters_atomically',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerSet_parameters_atomically,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.SetParametersAtomicallyRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceListenerSet_parameters_atomically =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceListenerSet_parameters_atomically',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerSet_parameters_atomically);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.SetParametersReq,
 *   !proto.rcl_interfaces.SetParametersRsp>}
 */
const methodDescriptor_Api_CallServiceFoxglove_bridgeSet_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceFoxglove_bridgeSet_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.SetParametersReq,
  rcl_interfaces_pb.SetParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.SetParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.SetParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.SetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.SetParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.SetParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceFoxglove_bridgeSet_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeSet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeSet_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.SetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.SetParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceFoxglove_bridgeSet_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeSet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeSet_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.ListParametersReq,
 *   !proto.rcl_interfaces.ListParametersRsp>}
 */
const methodDescriptor_Api_CallServiceService_server_02List_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceService_server_02List_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.ListParametersReq,
  rcl_interfaces_pb.ListParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.ListParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.ListParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.ListParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.ListParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.ListParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceService_server_02List_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceService_server_02List_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02List_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.ListParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.ListParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceService_server_02List_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceService_server_02List_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02List_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.DescribeParametersReq,
 *   !proto.rcl_interfaces.DescribeParametersRsp>}
 */
const methodDescriptor_Api_CallServiceFoxglove_bridgeDescribe_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceFoxglove_bridgeDescribe_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.DescribeParametersReq,
  rcl_interfaces_pb.DescribeParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.DescribeParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.DescribeParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.DescribeParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.DescribeParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.DescribeParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceFoxglove_bridgeDescribe_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeDescribe_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeDescribe_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.DescribeParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.DescribeParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceFoxglove_bridgeDescribe_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeDescribe_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeDescribe_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.SetParametersAtomicallyReq,
 *   !proto.rcl_interfaces.SetParametersAtomicallyRsp>}
 */
const methodDescriptor_Api_CallServiceService_server_02Set_parameters_atomically = new grpc.web.MethodDescriptor(
  '/Api/CallServiceService_server_02Set_parameters_atomically',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.SetParametersAtomicallyReq,
  rcl_interfaces_pb.SetParametersAtomicallyRsp,
  /**
   * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.SetParametersAtomicallyRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.SetParametersAtomicallyRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.SetParametersAtomicallyRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceService_server_02Set_parameters_atomically =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceService_server_02Set_parameters_atomically',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Set_parameters_atomically,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.SetParametersAtomicallyReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.SetParametersAtomicallyRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceService_server_02Set_parameters_atomically =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceService_server_02Set_parameters_atomically',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceService_server_02Set_parameters_atomically);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.GetParametersReq,
 *   !proto.rcl_interfaces.GetParametersRsp>}
 */
const methodDescriptor_Api_CallServiceFoxglove_bridgeGet_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceFoxglove_bridgeGet_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.GetParametersReq,
  rcl_interfaces_pb.GetParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.GetParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.GetParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.GetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.GetParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.GetParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceFoxglove_bridgeGet_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeGet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeGet_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.GetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.GetParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceFoxglove_bridgeGet_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceFoxglove_bridgeGet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceFoxglove_bridgeGet_parameters);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.rcl_interfaces.SetParametersReq,
 *   !proto.rcl_interfaces.SetParametersRsp>}
 */
const methodDescriptor_Api_CallServiceListenerSet_parameters = new grpc.web.MethodDescriptor(
  '/Api/CallServiceListenerSet_parameters',
  grpc.web.MethodType.UNARY,
  rcl_interfaces_pb.SetParametersReq,
  rcl_interfaces_pb.SetParametersRsp,
  /**
   * @param {!proto.rcl_interfaces.SetParametersReq} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  rcl_interfaces_pb.SetParametersRsp.deserializeBinary
);


/**
 * @param {!proto.rcl_interfaces.SetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.rcl_interfaces.SetParametersRsp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.rcl_interfaces.SetParametersRsp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ApiClient.prototype.callServiceListenerSet_parameters =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Api/CallServiceListenerSet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerSet_parameters,
      callback);
};


/**
 * @param {!proto.rcl_interfaces.SetParametersReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.rcl_interfaces.SetParametersRsp>}
 *     Promise that resolves to the response
 */
proto.ApiPromiseClient.prototype.callServiceListenerSet_parameters =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Api/CallServiceListenerSet_parameters',
      request,
      metadata || {},
      methodDescriptor_Api_CallServiceListenerSet_parameters);
};


module.exports = proto;

