Server: reportgrpc.guardeye.shawnsiu.site:5080
#Server: localhost:8080
LinkEndpoint: linkgrpc.guardeye.shawnsiu.site:5080
#LinkEndpoint: localhost:8080
Provider: []
Bridge:
  Enable: true
  Ip: 10.0.4.114
  Port: 8765
  Patterns:
    - "#"