Server: reportgrpc.guardeye.shawnsiu.site:5080
LinkEndpoint: linkgrpc.guardeye.shawnsiu.site:5080
Provider:
  - Type: ticker
    Args:
      Interval: 100000000000
Bridge:
  Enable: true
  Ip: 10.0.4.114
  Port: 8765