// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.4
// source: pkg_b.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	V    *V3    `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Pos) Reset() {
	*x = Pos{}
	mi := &file_pkg_b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_pkg_b_proto_rawDescGZIP(), []int{0}
}

func (x *Pos) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Pos) GetV() *V3 {
	if x != nil {
		return x.V
	}
	return nil
}

var File_pkg_b_proto protoreflect.FileDescriptor

var file_pkg_b_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6b, 0x67, 0x5f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x6b, 0x67, 0x5f, 0x62, 0x1a, 0x0b, 0x70, 0x6b, 0x67, 0x5f, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x32, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x01,
	0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x6b, 0x67, 0x5f, 0x61, 0x2e,
	0x56, 0x33, 0x52, 0x01, 0x76, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_b_proto_rawDescOnce sync.Once
	file_pkg_b_proto_rawDescData = file_pkg_b_proto_rawDesc
)

func file_pkg_b_proto_rawDescGZIP() []byte {
	file_pkg_b_proto_rawDescOnce.Do(func() {
		file_pkg_b_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_b_proto_rawDescData)
	})
	return file_pkg_b_proto_rawDescData
}

var file_pkg_b_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_b_proto_goTypes = []any{
	(*Pos)(nil), // 0: pkg_b.Pos
	(*V3)(nil),  // 1: pkg_a.V3
}
var file_pkg_b_proto_depIdxs = []int32{
	1, // 0: pkg_b.Pos.v:type_name -> pkg_a.V3
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_b_proto_init() }
func file_pkg_b_proto_init() {
	if File_pkg_b_proto != nil {
		return
	}
	file_pkg_a_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_b_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_b_proto_goTypes,
		DependencyIndexes: file_pkg_b_proto_depIdxs,
		MessageInfos:      file_pkg_b_proto_msgTypes,
	}.Build()
	File_pkg_b_proto = out.File
	file_pkg_b_proto_rawDesc = nil
	file_pkg_b_proto_goTypes = nil
	file_pkg_b_proto_depIdxs = nil
}
