// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.4
// source: shawn_define.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *V2       `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B *V2       `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C []int64   `protobuf:"varint,3,rep,packed,name=c,proto3" json:"c,omitempty"`
	D float64   `protobuf:"fixed64,4,opt,name=d,proto3" json:"d,omitempty"`
	E []float64 `protobuf:"fixed64,5,rep,packed,name=e,proto3" json:"e,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	mi := &file_shawn_define_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_shawn_define_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_shawn_define_proto_rawDescGZIP(), []int{0}
}

func (x *AddReq) GetA() *V2 {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *AddReq) GetB() *V2 {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *AddReq) GetC() []int64 {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *AddReq) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *AddReq) GetE() []float64 {
	if x != nil {
		return x.E
	}
	return nil
}

type V2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *V2) Reset() {
	*x = V2{}
	mi := &file_shawn_define_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *V2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V2) ProtoMessage() {}

func (x *V2) ProtoReflect() protoreflect.Message {
	mi := &file_shawn_define_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V2.ProtoReflect.Descriptor instead.
func (*V2) Descriptor() ([]byte, []int) {
	return file_shawn_define_proto_rawDescGZIP(), []int{1}
}

func (x *V2) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *V2) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res *V2       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	C   []int64   `protobuf:"varint,2,rep,packed,name=c,proto3" json:"c,omitempty"`
	D   float64   `protobuf:"fixed64,3,opt,name=d,proto3" json:"d,omitempty"`
	E   []float64 `protobuf:"fixed64,4,rep,packed,name=e,proto3" json:"e,omitempty"`
}

func (x *AddRsp) Reset() {
	*x = AddRsp{}
	mi := &file_shawn_define_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRsp) ProtoMessage() {}

func (x *AddRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shawn_define_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRsp.ProtoReflect.Descriptor instead.
func (*AddRsp) Descriptor() ([]byte, []int) {
	return file_shawn_define_proto_rawDescGZIP(), []int{2}
}

func (x *AddRsp) GetRes() *V2 {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *AddRsp) GetC() []int64 {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *AddRsp) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *AddRsp) GetE() []float64 {
	if x != nil {
		return x.E
	}
	return nil
}

var File_shawn_define_proto protoreflect.FileDescriptor

var file_shawn_define_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x68, 0x61, 0x77, 0x6e, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x68, 0x61, 0x77, 0x6e, 0x5f, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x65, 0x22, 0x72, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x01,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x77, 0x6e, 0x5f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x32, 0x52, 0x01, 0x61, 0x12, 0x1e, 0x0a, 0x01,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x77, 0x6e, 0x5f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x32, 0x52, 0x01, 0x62, 0x12, 0x0c, 0x0a, 0x01,
	0x63, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x01, 0x65, 0x22, 0x20, 0x0a, 0x02, 0x56, 0x32, 0x12, 0x0c, 0x0a, 0x01,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x22, 0x56, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52,
	0x73, 0x70, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x68, 0x61, 0x77, 0x6e, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e, 0x56,
	0x32, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x01, 0x65,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shawn_define_proto_rawDescOnce sync.Once
	file_shawn_define_proto_rawDescData = file_shawn_define_proto_rawDesc
)

func file_shawn_define_proto_rawDescGZIP() []byte {
	file_shawn_define_proto_rawDescOnce.Do(func() {
		file_shawn_define_proto_rawDescData = protoimpl.X.CompressGZIP(file_shawn_define_proto_rawDescData)
	})
	return file_shawn_define_proto_rawDescData
}

var file_shawn_define_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shawn_define_proto_goTypes = []any{
	(*AddReq)(nil), // 0: shawn_define.AddReq
	(*V2)(nil),     // 1: shawn_define.V2
	(*AddRsp)(nil), // 2: shawn_define.AddRsp
}
var file_shawn_define_proto_depIdxs = []int32{
	1, // 0: shawn_define.AddReq.a:type_name -> shawn_define.V2
	1, // 1: shawn_define.AddReq.b:type_name -> shawn_define.V2
	1, // 2: shawn_define.AddRsp.res:type_name -> shawn_define.V2
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shawn_define_proto_init() }
func file_shawn_define_proto_init() {
	if File_shawn_define_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shawn_define_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shawn_define_proto_goTypes,
		DependencyIndexes: file_shawn_define_proto_depIdxs,
		MessageInfos:      file_shawn_define_proto_msgTypes,
	}.Build()
	File_shawn_define_proto = out.File
	file_shawn_define_proto_rawDesc = nil
	file_shawn_define_proto_goTypes = nil
	file_shawn_define_proto_depIdxs = nil
}
