// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: link.proto

package server

import (
	"context"

	"github.com/0x587/guardeye/link/internal/logic"
	"github.com/0x587/guardeye/link/internal/svc"
	"github.com/0x587/guardeye/link/link"
)

type LinkServer struct {
	svcCtx *svc.ServiceContext
	link.UnimplementedLinkServer
}

func NewLinkServer(svcCtx *svc.ServiceContext) *LinkServer {
	return &LinkServer{
		svcCtx: svcCtx,
	}
}

func (s *LinkServer) Link(stream link.Link_LinkServer) error {
	l := logic.NewLinkLogic(stream.Context(), s.svcCtx)
	return l.Link(stream)
}

func (s *LinkServer) LinkCall(ctx context.Context, in *link.LinkCallReq) (*link.LinkCallRsp, error) {
	l := logic.NewLinkCallLogic(ctx, s.svcCtx)
	return l.LinkCall(in)
}
