// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkg_b.proto

package pkg_b;

public final class PkgB {
  private PkgB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pkg_b.Pos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>.pkg_a.V3 v = 2;</code>
     * @return Whether the v field is set.
     */
    boolean hasV();
    /**
     * <code>.pkg_a.V3 v = 2;</code>
     * @return The v.
     */
    pkg_a.PkgA.V3 getV();
    /**
     * <code>.pkg_a.V3 v = 2;</code>
     */
    pkg_a.PkgA.V3OrBuilder getVOrBuilder();
  }
  /**
   * Protobuf type {@code pkg_b.Pos}
   */
  public static final class Pos extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pkg_b.Pos)
      PosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pos.newBuilder() to construct.
    private Pos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pos() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pos();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pkg_b.PkgB.internal_static_pkg_b_Pos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pkg_b.PkgB.internal_static_pkg_b_Pos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pkg_b.PkgB.Pos.class, pkg_b.PkgB.Pos.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int V_FIELD_NUMBER = 2;
    private pkg_a.PkgA.V3 v_;
    /**
     * <code>.pkg_a.V3 v = 2;</code>
     * @return Whether the v field is set.
     */
    @java.lang.Override
    public boolean hasV() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.pkg_a.V3 v = 2;</code>
     * @return The v.
     */
    @java.lang.Override
    public pkg_a.PkgA.V3 getV() {
      return v_ == null ? pkg_a.PkgA.V3.getDefaultInstance() : v_;
    }
    /**
     * <code>.pkg_a.V3 v = 2;</code>
     */
    @java.lang.Override
    public pkg_a.PkgA.V3OrBuilder getVOrBuilder() {
      return v_ == null ? pkg_a.PkgA.V3.getDefaultInstance() : v_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getV());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getV());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pkg_b.PkgB.Pos)) {
        return super.equals(obj);
      }
      pkg_b.PkgB.Pos other = (pkg_b.PkgB.Pos) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (hasV() != other.hasV()) return false;
      if (hasV()) {
        if (!getV()
            .equals(other.getV())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (hasV()) {
        hash = (37 * hash) + V_FIELD_NUMBER;
        hash = (53 * hash) + getV().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pkg_b.PkgB.Pos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pkg_b.PkgB.Pos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pkg_b.PkgB.Pos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pkg_b.PkgB.Pos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pkg_b.PkgB.Pos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pkg_b.PkgB.Pos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pkg_b.PkgB.Pos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pkg_b.Pos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pkg_b.Pos)
        pkg_b.PkgB.PosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pkg_b.PkgB.internal_static_pkg_b_Pos_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pkg_b.PkgB.internal_static_pkg_b_Pos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pkg_b.PkgB.Pos.class, pkg_b.PkgB.Pos.Builder.class);
      }

      // Construct using pkg_b.PkgB.Pos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getVFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        v_ = null;
        if (vBuilder_ != null) {
          vBuilder_.dispose();
          vBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pkg_b.PkgB.internal_static_pkg_b_Pos_descriptor;
      }

      @java.lang.Override
      public pkg_b.PkgB.Pos getDefaultInstanceForType() {
        return pkg_b.PkgB.Pos.getDefaultInstance();
      }

      @java.lang.Override
      public pkg_b.PkgB.Pos build() {
        pkg_b.PkgB.Pos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pkg_b.PkgB.Pos buildPartial() {
        pkg_b.PkgB.Pos result = new pkg_b.PkgB.Pos(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pkg_b.PkgB.Pos result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.v_ = vBuilder_ == null
              ? v_
              : vBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pkg_b.PkgB.Pos) {
          return mergeFrom((pkg_b.PkgB.Pos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pkg_b.PkgB.Pos other) {
        if (other == pkg_b.PkgB.Pos.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasV()) {
          mergeV(other.getV());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getVFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private pkg_a.PkgA.V3 v_;
      private com.google.protobuf.SingleFieldBuilderV3<
          pkg_a.PkgA.V3, pkg_a.PkgA.V3.Builder, pkg_a.PkgA.V3OrBuilder> vBuilder_;
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       * @return Whether the v field is set.
       */
      public boolean hasV() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       * @return The v.
       */
      public pkg_a.PkgA.V3 getV() {
        if (vBuilder_ == null) {
          return v_ == null ? pkg_a.PkgA.V3.getDefaultInstance() : v_;
        } else {
          return vBuilder_.getMessage();
        }
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      public Builder setV(pkg_a.PkgA.V3 value) {
        if (vBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          v_ = value;
        } else {
          vBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      public Builder setV(
          pkg_a.PkgA.V3.Builder builderForValue) {
        if (vBuilder_ == null) {
          v_ = builderForValue.build();
        } else {
          vBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      public Builder mergeV(pkg_a.PkgA.V3 value) {
        if (vBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            v_ != null &&
            v_ != pkg_a.PkgA.V3.getDefaultInstance()) {
            getVBuilder().mergeFrom(value);
          } else {
            v_ = value;
          }
        } else {
          vBuilder_.mergeFrom(value);
        }
        if (v_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      public Builder clearV() {
        bitField0_ = (bitField0_ & ~0x00000002);
        v_ = null;
        if (vBuilder_ != null) {
          vBuilder_.dispose();
          vBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      public pkg_a.PkgA.V3.Builder getVBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getVFieldBuilder().getBuilder();
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      public pkg_a.PkgA.V3OrBuilder getVOrBuilder() {
        if (vBuilder_ != null) {
          return vBuilder_.getMessageOrBuilder();
        } else {
          return v_ == null ?
              pkg_a.PkgA.V3.getDefaultInstance() : v_;
        }
      }
      /**
       * <code>.pkg_a.V3 v = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pkg_a.PkgA.V3, pkg_a.PkgA.V3.Builder, pkg_a.PkgA.V3OrBuilder> 
          getVFieldBuilder() {
        if (vBuilder_ == null) {
          vBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pkg_a.PkgA.V3, pkg_a.PkgA.V3.Builder, pkg_a.PkgA.V3OrBuilder>(
                  getV(),
                  getParentForChildren(),
                  isClean());
          v_ = null;
        }
        return vBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pkg_b.Pos)
    }

    // @@protoc_insertion_point(class_scope:pkg_b.Pos)
    private static final pkg_b.PkgB.Pos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pkg_b.PkgB.Pos();
    }

    public static pkg_b.PkgB.Pos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pos>
        PARSER = new com.google.protobuf.AbstractParser<Pos>() {
      @java.lang.Override
      public Pos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Pos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pos> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pkg_b.PkgB.Pos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pkg_b_Pos_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pkg_b_Pos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013pkg_b.proto\022\005pkg_b\032\013pkg_a.proto\")\n\003Pos" +
      "\022\014\n\004type\030\001 \001(\t\022\024\n\001v\030\002 \001(\0132\t.pkg_a.V3B\006Z\004" +
      "./pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pkg_a.PkgA.getDescriptor(),
        });
    internal_static_pkg_b_Pos_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pkg_b_Pos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pkg_b_Pos_descriptor,
        new java.lang.String[] { "Type", "V", });
    pkg_a.PkgA.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
