syntax = "proto3";

package FoxgloveService;
option go_package="/foxgloveService";

message CdrReadReq {
  string ros_schema = 1;
  string pb_schema = 2;
  string pb_type_name = 3;
  bytes cdr_data = 4;
}

message CdrReadRsp {
  bytes trans_data = 1;
  string json_data = 2;
}

message CdrWriteReq {
  string ros_schema = 1;
  string pb_schema = 2;
  string pb_type_name = 3;
  bytes trans_data = 4;
}

message CdrWriteRsp {
  bytes cdr_data = 1;
  string json_data = 2;
}

service FoxgloveService {
  rpc CdrRead (CdrReadReq) returns (CdrReadRsp);
  rpc CdrWrite (CdrWriteReq) returns (CdrWriteRsp);
}

